import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { ColorService } from '../src/color/color.service';
import { Color as ColorEnum } from '../src/color.constants';

// Comprehensive color mapping from DB colors to Color enum values
const colorMapping: Record<string, ColorEnum[]> = {
  // Basic colors
  'black': [ColorEnum.BLACK],
  'white': [ColorEnum.WHITE],
  'red': [ColorEnum.RED],
  'blue': [ColorEnum.BLUE],
  'green': [ColorEnum.GREEN],
  'yellow': [ColorEnum.YELLOW],
  'pink': [ColorEnum.PINK],
  'purple': [ColorEnum.PURPLE],
  'orange': [ColorEnum.ORANGE],
  'brown': [ColorEnum.BROWN],
  'grey': [ColorEnum.GREY],
  'gray': [ColorEnum.GREY],
  'beige': [ColorEnum.BEIGE],
  'navy': [ColorEnum.NAVY],
  'light blue': [ColorEnum.LIGHT_BLUE],
  'sky blue': [ColorEnum.SKY_BLUE],
  'dark blue': [ColorEnum.DARK_BLUE],
  'royal blue': [ColorEnum.ROYAL_BLUE],
  'sage': [ColorEnum.SAGE],
  'turquoise': [ColorEnum.TURQUOISE],
  'mint': [ColorEnum.MINT],
  'olive': [ColorEnum.OLIVE],
  'khaki': [ColorEnum.KHAKI],
  'camel': [ColorEnum.CAMEL],
  'mustard': [ColorEnum.MUSTARD],
  'coral': [ColorEnum.CORAL],
  'salmon': [ColorEnum.SALMON],
  'bordeaux': [ColorEnum.BORDEAUX],
  'lavender': [ColorEnum.LAVENDER],
  'lilac': [ColorEnum.LILAC],
  'charcoal': [ColorEnum.CHARCOAL],
  'ivory': [ColorEnum.IVORY],
  'off white': [ColorEnum.OFFWHITE],
  'cream': [ColorEnum.CREAM],
  'taupe': [ColorEnum.TAUPE],
  'gold': [ColorEnum.GOLD],
  'silver': [ColorEnum.SILVER],
  'copper': [ColorEnum.COPPER],
  'emerald': [ColorEnum.EMERLAD],
  'baby pink': [ColorEnum.BABY_PINK],
  'rose': [ColorEnum.ROSE],
  'tan': [ColorEnum.TAN],
  'nude': [ColorEnum.NUDE],
  'bronze': [ColorEnum.BRONZE],
  'mocha': [ColorEnum.MOCHA],
  'stone': [ColorEnum.STONE],
  'indigo': [ColorEnum.INDIGO],

  // Hebrew colors
  'שחור': [ColorEnum.BLACK],
  'לבן': [ColorEnum.WHITE],
  'אדום': [ColorEnum.RED],
  'כחול': [ColorEnum.BLUE],
  'ירוק': [ColorEnum.GREEN],
  'צהוב': [ColorEnum.YELLOW],
  'ורוד': [ColorEnum.PINK],
  'סגול': [ColorEnum.PURPLE],
  'כתום': [ColorEnum.ORANGE],
  'חום': [ColorEnum.BROWN],
  'אפור': [ColorEnum.GREY],
  'בז': [ColorEnum.BEIGE],
  'בז׳': [ColorEnum.BEIGE],
  'בז\'': [ColorEnum.BEIGE],
  'בז״': [ColorEnum.BEIGE],
  'שנהב': [ColorEnum.IVORY],
  'זהב': [ColorEnum.GOLD],
  'כסף': [ColorEnum.SILVER],
  'נחושת': [ColorEnum.COPPER],
  'אמרלד': [ColorEnum.EMERLAD],
  'ורוד בהיר': [ColorEnum.BABY_PINK],
  'ורוד בייבי': [ColorEnum.BABY_PINK],
  'עירום': [ColorEnum.NUDE],
  'ארד': [ColorEnum.BRONZE],
  'מוקה': [ColorEnum.MOCHA],
  'אבן': [ColorEnum.STONE],
  'זית': [ColorEnum.OLIVE],
  'חרדל': [ColorEnum.MUSTARD],
  'קורל': [ColorEnum.CORAL],
  'בורדו': [ColorEnum.BORDEAUX],
  'בורדו׳': [ColorEnum.BORDEAUX],
  'לילך': [ColorEnum.LILAC],
  'חאקי': [ColorEnum.KHAKI],
  'קאקי': [ColorEnum.KHAKI],
  'קאמל': [ColorEnum.CAMEL],
  'כאמל': [ColorEnum.CAMEL],
  'טורקיז': [ColorEnum.TURQUOISE],
  'מנטה': [ColorEnum.MINT],
  'מרווה': [ColorEnum.SAGE],
  'אפרסק': [ColorEnum.CORAL],
  'חמרה': [ColorEnum.BROWN],
  'חמרה.': [ColorEnum.BROWN],
  'רובי': [ColorEnum.RED],
  'אגוז': [ColorEnum.BROWN],
  'שוקולד': [ColorEnum.BROWN],
  'קפה': [ColorEnum.BROWN],
  'אדמה': [ColorEnum.BROWN],
  'חול': [ColorEnum.BEIGE],
  'חול לבן': [ColorEnum.WHITE],
  'אדום עתיק': [ColorEnum.RED],
  'אדום תות': [ColorEnum.RED],
  'אדום אש': [ColorEnum.RED],
  'אדום בהיר': [ColorEnum.RED],
  'אדום מינרל': [ColorEnum.RED],
  'ירוק בהיר': [ColorEnum.GREEN],
  'ירוק כהה': [ColorEnum.GREEN],
  'ירוק דשא': [ColorEnum.GREEN],
  'ירוק תפוח': [ColorEnum.GREEN],
  'ירוק ליים': [ColorEnum.GREEN],
  'ירוק בקבוק': [ColorEnum.GREEN],
  'ירוק אייסברג': [ColorEnum.GREEN],
  'ירוק צבאי': [ColorEnum.GREEN],
  'ירוק חאקי': [ColorEnum.GREEN],
  'ירוק ברוש': [ColorEnum.GREEN],
  'ירוק קמופלאז\'': [ColorEnum.GREEN],
  'ירוק קמופלאז': [ColorEnum.GREEN],
  'ירוק יער': [ColorEnum.GREEN],
  'ירוק מנטה': [ColorEnum.GREEN],
  'ירוק עמוק': [ColorEnum.GREEN],
  'ירוק צהבהב': [ColorEnum.GREEN],
  'ירוק מרווה': [ColorEnum.GREEN],
  'ירוק טורקיז': [ColorEnum.GREEN],
  'כחול בהיר': [ColorEnum.LIGHT_BLUE],
  'כחול כהה': [ColorEnum.DARK_BLUE],
  'כחול שמיים': [ColorEnum.SKY_BLUE],
  'כחול ים': [ColorEnum.BLUE],
  'כחול אוקיינוס': [ColorEnum.BLUE],
  'כחול עתיק': [ColorEnum.BLUE],
  'כחול דהוי': [ColorEnum.BLUE],
  'כחול מאובק': [ColorEnum.BLUE],
  'כחול עננים': [ColorEnum.LIGHT_BLUE],
  'כחול קרח': [ColorEnum.LIGHT_BLUE],
  'כחול פלדה': [ColorEnum.BLUE],
  'כחול קובלט': [ColorEnum.BLUE],
  'כחול גינס': [ColorEnum.DENIM],
  'כחול ג\'ינס': [ColorEnum.DENIM],
  'כחול וירוק': [ColorEnum.BLUE, ColorEnum.GREEN],
  'כחול ווש': [ColorEnum.BLUE],
  'כחול בי"ס': [ColorEnum.BLUE],
  'כחול 51': [ColorEnum.BLUE],
  'כחול - שחור': [ColorEnum.BLUE, ColorEnum.BLACK],
  'כחול/שחור': [ColorEnum.BLUE, ColorEnum.BLACK],
  'כחול/לבן': [ColorEnum.BLUE, ColorEnum.WHITE],
  'כחול־ים': [ColorEnum.BLUE],
  'כחול־שמיים': [ColorEnum.SKY_BLUE],
  'כחול־שמיים בהיר': [ColorEnum.SKY_BLUE],
  'כחול־שחור': [ColorEnum.BLUE, ColorEnum.BLACK],
  'כחול שחור': [ColorEnum.BLUE, ColorEnum.BLACK],
  'כחול תינוק': [ColorEnum.LIGHT_BLUE],
  'כחול מלאנז\'': [ColorEnum.NAVY],
  'כחול מלאנז׳': [ColorEnum.NAVY],
  'כחול מלאנז': [ColorEnum.NAVY],
  
  // Additional colors from the provided list
  'סחלב': [ColorEnum.PURPLE],
  'silver blue': [ColorEnum.LIGHT_BLUE],
  'dark green': [ColorEnum.GREEN],
  'blue heather stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'green heather': [ColorEnum.GREEN],
  'light heather blue': [ColorEnum.LIGHT_BLUE],
  'sand strata': [ColorEnum.BEIGE],
  'אופוויט מלאנז': [ColorEnum.OFFWHITE],
  'light cast': [ColorEnum.WHITE],
  'pale pink': [ColorEnum.BABY_PINK],
  'shiny gold / gradient smoke': [ColorEnum.GOLD],
  'grey two': [ColorEnum.GREY],
  'green floral': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'shameless': [ColorEnum.RED],
  'אייריש קרים': [ColorEnum.CREAM],
  'dark night navy / calico stripe': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'transparent dark brown / gradient smoke to blue to trans': [ColorEnum.BROWN, ColorEnum.TRANSPARENT],
  'dark burgundy / gradient smoke': [ColorEnum.BORDEAUX],
  'washed denim/starch blue': [ColorEnum.WASHED_DENIM],
  'sun': [ColorEnum.YELLOW],
  'copenhagen blue': [ColorEnum.BLUE],
  'french purple': [ColorEnum.PURPLE],
  '2': [],
  'highland khaki': [ColorEnum.KHAKI],
  'blue argyle': [ColorEnum.BLUE, ColorEnum.CHECKED],
  'lemon zest multi stripe': [ColorEnum.YELLOW, ColorEnum.STRIPED],
  'halo mint': [ColorEnum.MINT],
  'light heather grey print': [ColorEnum.GREY],
  'military-green': [ColorEnum.GREEN],
  'citronella/optic white': [ColorEnum.GREEN, ColorEnum.WHITE],
  'לאטה': [ColorEnum.BEIGE],
  'bright medium wash': [ColorEnum.DENIM],
  '4.7 cool beige': [ColorEnum.BEIGE],
  'demi trans blue': [ColorEnum.BLUE, ColorEnum.TRANSPARENT],
  'dark brown': [ColorEnum.BROWN],
  'cherry red check': [ColorEnum.RED, ColorEnum.CHECKED],
  'frozen custard': [ColorEnum.CREAM],
  'teaberry blossom': [ColorEnum.PINK],
  'ורוד קורל': [ColorEnum.CORAL],
  'white floral': [ColorEnum.WHITE, ColorEnum.FLORAL],
  'faded ink': [ColorEnum.BLUE],
  'mauve': [ColorEnum.PURPLE],
  'faded navy': [ColorEnum.NAVY],
  'matt brown / gradient dark blue to grey': [ColorEnum.BROWN],
  'rinse': [ColorEnum.BLUE],
  '0.3 ivory silk': [ColorEnum.IVORY],
  'navy-white': [ColorEnum.NAVY, ColorEnum.WHITE],
  'authentic marl grey': [ColorEnum.GREY],
  'rooted brown': [ColorEnum.BROWN],
  'carbon navy': [ColorEnum.NAVY],
  'shiny silver': [ColorEnum.SILVER],
  'butter yellow': [ColorEnum.YELLOW],
  'neutral stripe': [ColorEnum.GREY, ColorEnum.STRIPED],
  'lucent white/multi': [ColorEnum.WHITE, ColorEnum.MULTICOLOR],
  'sandy pink met.': [ColorEnum.PINK],
  'light blue floral': [ColorEnum.LIGHT_BLUE, ColorEnum.FLORAL],
  'copenhagen blue/optic white stripe': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.STRIPED],
  'battle green heather': [ColorEnum.GREEN],
  'silver metallic': [ColorEnum.SILVER, ColorEnum.METALLIC],
  'fandango pink stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'light brown heather': [ColorEnum.BROWN],
  'cherry red print': [ColorEnum.RED],
  'shiny dark gun / gradient dark blue to grey': [ColorEnum.BLACK, ColorEnum.GREY],
  'sage green stripe': [ColorEnum.SAGE, ColorEnum.GREEN, ColorEnum.STRIPED],
  'calico / dark night navy stripe': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'lucid lime': [ColorEnum.GREEN, ColorEnum.YELLOW],
  'אקליפטוס': [ColorEnum.GREEN],
  'oatmeal heather': [ColorEnum.BEIGE],
  'lake blue': [ColorEnum.BLUE],
  'solar pink': [ColorEnum.PINK],
  'פטרול': [ColorEnum.BLUE],
  'black-white-transparent nude/gradient smoke': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.TRANSPARENT],
  'periwinkle': [ColorEnum.PURPLE],
  'chalk white': [ColorEnum.WHITE],
  'שחור אטום': [ColorEnum.BLACK],
  'navy/white stripe': [ColorEnum.NAVY, ColorEnum.WHITE, ColorEnum.STRIPED],
  'demi stripes': [ColorEnum.STRIPED],
  'white floral pattern': [ColorEnum.WHITE, ColorEnum.FLORAL],
  '04': [],
  'white stripe': [ColorEnum.WHITE, ColorEnum.STRIPED],
  'ecru / beige stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'pearl': [ColorEnum.WHITE],
  'dark trans burgundy / gradient smoke': [ColorEnum.BORDEAUX, ColorEnum.TRANSPARENT],
  'silver / gradient smoke to blue to trans': [ColorEnum.SILVER],
  'cradle pink multi stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'black-gold/gradient smoke': [ColorEnum.BLACK, ColorEnum.GOLD],
  'shiny light gold/milky grey demi': [ColorEnum.GOLD],
  'שחור ולבן': [ColorEnum.BLACK, ColorEnum.WHITE],
  'עידו': [ColorEnum.BLUE],
  'glacier green': [ColorEnum.GREEN],
  'light mocha': [ColorEnum.MOCHA],
  'white ripped': [ColorEnum.WHITE],
  'pool party/rock melon': [ColorEnum.GREEN],
  'earth strata': [ColorEnum.BROWN],
  'navy heather': [ColorEnum.NAVY],
  'black / black / black': [ColorEnum.BLACK],
  'warm ice grey heather': [ColorEnum.GREY],
  'light ripped stripe': [ColorEnum.GREY],
  'white print': [ColorEnum.WHITE],
  'demi havana / gradient brown': [ColorEnum.BEIGE],
  'dk jeansblue melange': [ColorEnum.BEIGE],
  'legend ink': [ColorEnum.GREEN],
  'garden rose stripe': [ColorEnum.GREEN],
  'light dd': [ColorEnum.LIGHT_BLUE],
  '01': [ColorEnum.BLACK],
  'silt': [ColorEnum.BEIGE],
  'blue_navy': [ColorEnum.BLUE],
  'shiny gold': [ColorEnum.GOLD],
  'קרח': [ColorEnum.LIGHT_BLUE],
  'בז\' חזק': [ColorEnum.BEIGE],
  'yellow floral': [ColorEnum.YELLOW],
  'icy pink': [ColorEnum.PINK],
  'dark medium wash': [ColorEnum.BROWN],
  '02': [ColorEnum.BLACK],
  'bone': [ColorEnum.BEIGE],
  'demi brown beige blue': [ColorEnum.BEIGE],
  'tropical floral sweet blue': [ColorEnum.PINK],
  'black/ivory': [ColorEnum.BLACK, ColorEnum.WHITE],
  '2w0 beige': [ColorEnum.BEIGE],
  'deep black': [ColorEnum.BLACK],
  'powder teal': [ColorEnum.BLUE],
  'bank blue stripe': [ColorEnum.BLUE],
  'משמש': [ColorEnum.GREEN],
  'mineral': [ColorEnum.GREEN],
  'team power red 2': [ColorEnum.PINK],
  'צהוב חרדל': [ColorEnum.PURPLE],
  'true purple': [ColorEnum.PURPLE],
  'antracite': [ColorEnum.BLACK],
  'basket brown': [ColorEnum.BROWN],
  'night indigo': [ColorEnum.NAVY],
  '1.5 cream': [ColorEnum.BEIGE],
  'dark night navy': [ColorEnum.NAVY],
  'pale yellow': [ColorEnum.YELLOW],
  'rubber black / gradient turquoise to transparent': [ColorEnum.BLUE],
  'mulberry': [ColorEnum.PURPLE],
  'צבעוני אדום': [ColorEnum.RED],
  'driftwood': [ColorEnum.BROWN],
  'wonder white': [ColorEnum.WHITE],
  '31  ?le d`amour': [ColorEnum.PINK],
  'dark night navy / ivory stripe': [ColorEnum.NAVY, ColorEnum.WHITE],
  'pink stripe': [ColorEnum.PINK],
  'white plaid': [ColorEnum.WHITE],
  'brown wood / gradient brown to smoke': [ColorEnum.BROWN],
  'sandalwood stripe': [ColorEnum.BROWN],
  'khaki stripe': [ColorEnum.KHAKI],
  'shiny light gold/matt black / gradient smoke': [ColorEnum.GOLD],
  'heathered oatmilk': [ColorEnum.BEIGE],
  'pollen yellow stripe': [ColorEnum.YELLOW],
  'warm gray': [ColorEnum.BEIGE],
  'midnight turquoise': [ColorEnum.BLUE],
  'crater blue': [ColorEnum.BLUE],
  'classic pink/optic white stripe': [ColorEnum.PINK, ColorEnum.WHITE],
  'matt dark burgundy / gradient brown': [ColorEnum.BROWN],
  'Mustard, dark cream and cream': [ColorEnum.YELLOW],
  'flora medley multi': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'desert sand dune': [ColorEnum.BEIGE],
  'sandy pink mel': [ColorEnum.PINK],
  'heathered blue': [ColorEnum.BROWN],
  'light beige/ancient white': [ColorEnum.BEIGE],
  'dark pink floral': [ColorEnum.PURPLE],
  'white camo': [ColorEnum.WHITE],
  'medium blue heather stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'taupe pattern': [ColorEnum.BEIGE],
  'light pink print': [ColorEnum.PINK],
  'הדפס שחור-לבן': [ColorEnum.BLACK, ColorEnum.WHITE],
  'ocean smoke to brown': [ColorEnum.BEIGE],
  'italian wine': [ColorEnum.YELLOW],
  'faded olive stripe': [ColorEnum.GREEN],
  'green heather stripe': [ColorEnum.GREEN],
  'newsprint / light grey': [ColorEnum.GREY],
  'pink poppy': [ColorEnum.PINK],
  'light grey heather': [ColorEnum.GREY],
  'pinecone tan': [ColorEnum.BROWN],
  'ivory petal/grey heather stripe': [ColorEnum.WHITE, ColorEnum.GREY],
  'red plaid': [ColorEnum.RED],
  'light green print': [ColorEnum.GREEN],
  'golden champagne / solid yellow beige': [ColorEnum.YELLOW],
  'medieval': [ColorEnum.BLACK],
  'shiny trans olive': [ColorEnum.GREEN],
  'red / white / navy': [ColorEnum.RED, ColorEnum.WHITE, ColorEnum.BLUE],
  'ecru / radiant green stripe': [ColorEnum.BEIGE, ColorEnum.GREEN],
  'red heather': [ColorEnum.RED],
  'sandy beige/cerulean aqua': [ColorEnum.BEIGE, ColorEnum.BLUE],
  'brown-brown-brown': [ColorEnum.BROWN],
  'miami aqua stripe': [ColorEnum.BLUE],
  '1w0 ecru': [ColorEnum.BEIGE],
  'דנים': [ColorEnum.BLACK],
  'minty essence': [ColorEnum.MINT],
  '20 invite only': [ColorEnum.BLACK],
  'light brown camo': [ColorEnum.BROWN],
  'gold/gradient turquoise to transparent': [ColorEnum.GOLD, ColorEnum.BLUE],
  'warm clay': [ColorEnum.BROWN],
  'ורוד בוהק': [ColorEnum.PINK],
  'black / gradient brown': [ColorEnum.BLACK, ColorEnum.BROWN],
  'washed black carpenter': [ColorEnum.BLACK],
  'natural/black': [ColorEnum.BLACK],
  'washed dark green': [ColorEnum.GREEN],
  'hickory': [ColorEnum.BROWN],
  'dark football gold': [ColorEnum.RED],
  'black-nude': [ColorEnum.BLACK, ColorEnum.NUDE],
  'sugarcane': [ColorEnum.GREEN],
  'sky captain / bright white / rosewater': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.PINK],
  'פסים חומים': [ColorEnum.BLACK],
  'charcoal grey': [ColorEnum.GREY],
  'hydrogen grey': [ColorEnum.GREY],
  'wedge blue': [ColorEnum.BLUE],
  'light': [ColorEnum.BLACK],
  'calico/navy stripe': [ColorEnum.BLUE, ColorEnum.NAVY],
  'black and dark slate': [ColorEnum.BLACK, ColorEnum.NAVY],
  'mint green print': [ColorEnum.GREEN],
  'dark blue denim': [ColorEnum.DARK_BLUE],
  'gold/gradient smoke to beige': [ColorEnum.GOLD, ColorEnum.BEIGE],
  'opal green': [ColorEnum.GREEN],
  'פסים ורודים': [ColorEnum.PINK],
  'bliss orange': [ColorEnum.PINK],
  'זית מעושן': [ColorEnum.BROWN],
  'semi solar slime': [ColorEnum.GREEN],
  'medium dark wash': [ColorEnum.BROWN],
  'light lilac locket print': [ColorEnum.PURPLE],
  '131 burnt peach (fn)': [ColorEnum.RED],
  'navy blue dot': [ColorEnum.BLUE],
  'claystone': [ColorEnum.BROWN],
  'beige brown stripes / gradient dark brown/light brown': [ColorEnum.BEIGE, ColorEnum.BROWN],
  'ורוד עתיק': [ColorEnum.RED],
  'מנוחש': [ColorEnum.BROWN],
  'birch heather': [ColorEnum.BEIGE],
  'matt black/gradient smoke': [ColorEnum.BLACK, ColorEnum.GREY],
  'brown beige demi/gradient brown': [ColorEnum.BROWN, ColorEnum.BEIGE],
  'gold / gradient light green to trans': [ColorEnum.GOLD, ColorEnum.GREEN],
  'aegean sea': [ColorEnum.BLUE],
  'night brown': [ColorEnum.BLACK],
  'preloved fig': [ColorEnum.BEIGE],
  'white tint': [ColorEnum.WHITE],
  'matt black/matt dark blue / blue revo smoke': [ColorEnum.BLACK, ColorEnum.BLACK, ColorEnum.BLUE],
  'teaberry blossom stripe': [ColorEnum.PINK],
  'multi coloured': [ColorEnum.MULTICOLOR],
  'demi leo / gradient smoke': [ColorEnum.PURPLE, ColorEnum.GREEN],
  'beechwood stripe': [ColorEnum.BROWN],
  'solid sage / gradient smoke': [ColorEnum.SAGE],
  'black / gradient green to yellow': [ColorEnum.BLACK, ColorEnum.GREEN],
  'black and light lilac': [ColorEnum.BLACK, ColorEnum.LIGHT_BLUE],
  'all stars aop': [ColorEnum.BLACK],
  'silver dawn': [ColorEnum.SILVER],
  'blue check': [ColorEnum.BLUE],
  'coastal taupe': [ColorEnum.BEIGE],
  'light grey sd/texture': [ColorEnum.GREY],
  'medium ripped wash': [ColorEnum.BROWN],
  'בז\' אפרפר': [ColorEnum.BEIGE],
  'faded indigo stripe': [ColorEnum.BLUE],
  '103 irresistible': [ColorEnum.PINK],
  'rose gold/ milky dark nude / ocean dk.red to light brown': [ColorEnum.PINK, ColorEnum.NUDE, ColorEnum.BLUE],
  'misty sage': [ColorEnum.GREY],
  'vintage blue': [ColorEnum.BLUE],
  'light pink plaid': [ColorEnum.PINK],
  'מולטי 4': [ColorEnum.MULTICOLOR],
  'precious pink/optic white': [ColorEnum.PINK, ColorEnum.WHITE],
  'lucid lemon': [ColorEnum.GREEN],
  'washed blue': [ColorEnum.BLUE],
  'better scarlet': [ColorEnum.RED],
  'grey three': [ColorEnum.GREY],
  'burgundy velvet': [ColorEnum.PURPLE],
  'black dd': [ColorEnum.BLACK],
  'tiger demi / gradient brown': [ColorEnum.RED, ColorEnum.PURPLE],
  'white/breezy blue': [ColorEnum.WHITE, ColorEnum.BLUE],
  'medium blue heather': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'white and black': [ColorEnum.WHITE, ColorEnum.BLACK],
  'vision grey': [ColorEnum.GREY],
  'light ivory': [ColorEnum.WHITE],
  'powder blue ombre': [ColorEnum.BLUE, ColorEnum.BEIGE],
  'desert brown': [ColorEnum.BROWN],
  'sage green': [ColorEnum.GREEN],
  'preloved crimson': [ColorEnum.RED],
  'optic white stripe': [ColorEnum.WHITE],
  'persian blue': [ColorEnum.BLUE],
  'רוגע': [ColorEnum.PURPLE],
  'sailor navy': [ColorEnum.NAVY],
  'pink floral': [ColorEnum.PINK],
  'classic beige': [ColorEnum.BEIGE],
  '2600b1': [ColorEnum.BLACK],
  'פסים כפולים': [ColorEnum.BLACK],
  'tartan green': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'olive camo': [ColorEnum.GREEN, ColorEnum.KHAKI],
  'batique khaki': [ColorEnum.KHAKI, ColorEnum.METALLIC],
  'brown demi / gradient brown to nude': [ColorEnum.BROWN, ColorEnum.BEIGE],
  'medium ripped': [ColorEnum.BROWN],
  'faded indigo/grey stripe': [ColorEnum.BLUE, ColorEnum.GREY],
  'light  blue stripe': [ColorEnum.LIGHT_BLUE],
  'Dark Denim': [ColorEnum.DARK_BLUE],
  'trans dark champagne- gold / gradient dark smoke brown to brown orange to trans': [ColorEnum.DARK_BLUE, ColorEnum.GOLD, ColorEnum.BEIGE],
  'grey / red / blue': [ColorEnum.GREY, ColorEnum.RED, ColorEnum.BLUE],
  'light heather cream': [ColorEnum.BEIGE, ColorEnum.GREY],
  'light pink camo': [ColorEnum.PINK, ColorEnum.BEIGE],
  'trans light champagne': [ColorEnum.BLUE, ColorEnum.TRANSPARENT],
  'mulberry plaid': [ColorEnum.PURPLE, ColorEnum.BLUE],
  'פסים נייבי ותכלת': [ColorEnum.BLUE, ColorEnum.WHITE],
  'semolina heather': [ColorEnum.BEIGE],
  'ecru/red/blue stripe': [ColorEnum.BEIGE, ColorEnum.RED, ColorEnum.BLUE],
  'strawberry field stripe': [ColorEnum.PINK],
  'college purple': [ColorEnum.PURPLE],
  'heather oatmeal': [ColorEnum.BEIGE],
  'slate check': [ColorEnum.BLACK, ColorEnum.GREY],
  'cypress green': [ColorEnum.GREEN],
  'white-black': [ColorEnum.WHITE, ColorEnum.BLACK],
  'oatmeal': [ColorEnum.BEIGE],
  'light heather gray': [ColorEnum.GREY],
  'sheer oak/mojave tan': [ColorEnum.BEIGE, ColorEnum.BROWN],
  'ripped cream': [ColorEnum.WHITE],
  'solar gold': [ColorEnum.YELLOW],
  'light oatmeal heather': [ColorEnum.BEIGE],
  'silver pebble': [ColorEnum.SILVER],
  'graphite grey/graphite grey/graphite grey': [ColorEnum.GREY],
  'washed light brown': [ColorEnum.BEIGE],
  'collegiate purple': [ColorEnum.BLUE],
  'ecru': [ColorEnum.BEIGE],
  'dark medium': [ColorEnum.BROWN],
  'green grey': [ColorEnum.GREEN, ColorEnum.BEIGE],
  'ג\'ינס כהה': [ColorEnum.BROWN],
  'red / white stripe': [ColorEnum.RED, ColorEnum.WHITE],
  'חום־אדמדם': [ColorEnum.BROWN, ColorEnum.GREEN],
  'navy blue pattern': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'beige silt stripe': [ColorEnum.BEIGE, ColorEnum.GREY],
  'pewter': [ColorEnum.GREY],
  'flame red': [ColorEnum.RED],
  'light tan painter': [ColorEnum.BROWN],
  'medium grey heather': [ColorEnum.GREY],
  'shirt blue check': [ColorEnum.BLUE, ColorEnum.RED],
  'silver / gradient smoke to dark turquoise to trans': [ColorEnum.SILVER, ColorEnum.BLUE],
  'light purple': [ColorEnum.PURPLE],
  'light blue denim': [ColorEnum.LIGHT_BLUE],
  'grey four': [ColorEnum.GREY],
  'light pink stripe': [ColorEnum.PINK],
  'dark sky blue': [ColorEnum.BLUE],
  'trans brown grey / g15': [ColorEnum.BLUE, ColorEnum.BEIGE],
  'light tint': [ColorEnum.BLACK],
  'mountain mist': [ColorEnum.BLUE],
  'matt black': [ColorEnum.BLACK],
  'בטון': [ColorEnum.BLACK],
  'pink lily': [ColorEnum.PINK],
  'legacy brown': [ColorEnum.BEIGE],
  'זהב שקוף': [ColorEnum.GOLD],
  'light medium ripped': [ColorEnum.BROWN],
  'aurora met.': [ColorEnum.PURPLE],
  'canary': [ColorEnum.YELLOW],
  'black ripped': [ColorEnum.BLACK],
  'shadow navy': [ColorEnum.NAVY],
  'light yellow': [ColorEnum.YELLOW],
  'מנומר': [ColorEnum.BLACK],
  'grey skies': [ColorEnum.GREY],
  'דנים כהה': [ColorEnum.BLACK],
  'פרחוני': [ColorEnum.PURPLE],
  'נטורל': [ColorEnum.BLACK],
  'shadow violet': [ColorEnum.PURPLE],
  'purple rush / cloud white / lucid lemon': [ColorEnum.PURPLE, ColorEnum.WHITE, ColorEnum.GREEN],
  'sweet blue/white': [ColorEnum.BEIGE, ColorEnum.WHITE],
  'lilac spring stripe': [ColorEnum.PURPLE, ColorEnum.GREEN],
  'trans light champagne / gradient smoke to beige': [ColorEnum.BLUE, ColorEnum.BEIGE],
  'בזוקה': [ColorEnum.PINK],
  'white with strawberries': [ColorEnum.WHITE, ColorEnum.PINK],
  'ורד': [ColorEnum.PINK],
  'rosey peach': [ColorEnum.PINK],
  '04 uninhibited': [ColorEnum.PINK],
  'demi brown stripes / gradient smoke': [ColorEnum.BROWN, ColorEnum.PURPLE],
  'demi brown stripes / gradient brown': [ColorEnum.BROWN, ColorEnum.PURPLE],
  'butter yellow pattern': [ColorEnum.YELLOW],
  'breezy blue/navy': [ColorEnum.BLUE, ColorEnum.BEIGE],
  'keepsake blue multi stripe': [ColorEnum.BLUE, ColorEnum.WHITE],
  'midnight breeze': [ColorEnum.PURPLE],
  'osprey blu': [ColorEnum.BLUE],
  'אפור כהה': [ColorEnum.BROWN],
  'carmine red': [ColorEnum.RED],
  'פסים נייבי': [ColorEnum.BLACK],
  'matt trans dark burgundy': [ColorEnum.BORDEAUX, ColorEnum.TRANSPARENT],
  'black on gold with crystal stones / gradient brown': [ColorEnum.BLACK, ColorEnum.GOLD, ColorEnum.WHITE],
  'light pink heather': [ColorEnum.PINK, ColorEnum.BEIGE],
  'seashore blue': [ColorEnum.BLUE],
  'new vintage khaki': [ColorEnum.KHAKI],
  'פחם': [ColorEnum.BLACK],
  'hydrogen grey stripe': [ColorEnum.GREY],
  'ספריי': [ColorEnum.BLACK],
  '05 front page': [ColorEnum.BLACK],
  'peach dusk multi stripe': [ColorEnum.PINK, ColorEnum.BEIGE],
  'green plaid': [ColorEnum.GREEN],
  'chambray': [ColorEnum.BLUE],
  'blue denim': [ColorEnum.BLUE],
  'popcorn': [ColorEnum.YELLOW],
  'gentle gold': [ColorEnum.YELLOW],
  'team dark green': [ColorEnum.GREEN],
  'preloved green': [ColorEnum.GREEN],
  'soothing s': [ColorEnum.GREEN],
  '05 getaway': [ColorEnum.PURPLE],
  'sleepy blue multi': [ColorEnum.BLUE, ColorEnum.PURPLE],
  'peach dusk/blue stripe': [ColorEnum.PINK, ColorEnum.BLUE],
  'טפיוקה': [ColorEnum.BEIGE],
  'beige trench': [ColorEnum.BEIGE],
  'dazzling blue stripe': [ColorEnum.BLUE],
  'charming green stripe': [ColorEnum.GREEN],
  'indigo denim': [ColorEnum.BLUE],
  'washed denim': [ColorEnum.BLUE],
  'light blue check': [ColorEnum.LIGHT_BLUE],
  'dark_gray': [ColorEnum.GREY],
  'black/highlight yellow': [ColorEnum.BLACK, ColorEnum.YELLOW],
  'brown beige milky brown/gradient brown': [ColorEnum.BROWN, ColorEnum.BEIGE, ColorEnum.GREY],
  'shiny light gold': [ColorEnum.GOLD],
  'espresso check': [ColorEnum.BLACK],
  'fierce red': [ColorEnum.RED],
  'stone / gradient smoke': [ColorEnum.BLACK],
  'light powder blue': [ColorEnum.BLUE],
  'new beige / gradient smoke': [ColorEnum.BEIGE],
  'eggshell': [ColorEnum.WHITE],
  'charcoal gray': [ColorEnum.BLACK],
  'beige demi': [ColorEnum.BEIGE],
  'fall mint': [ColorEnum.GREEN],
  'raspberry - rose quartz': [ColorEnum.RED, ColorEnum.PURPLE],
  'charm pink': [ColorEnum.PINK],
  'shadow olive': [ColorEnum.GREEN],
  'coral red': [ColorEnum.PURPLE],
  'oasis': [ColorEnum.PINK],
  'dry sand': [ColorEnum.BEIGE],
  'מאטצה': [ColorEnum.BROWN],
  'atlantic blue': [ColorEnum.BLUE],
  'blue moment check': [ColorEnum.BLUE],
  'ancient white stripe': [ColorEnum.WHITE],
  'stoney/black': [ColorEnum.BLACK],
  'cloud blue': [ColorEnum.BLUE],
  'harbor cove stripe': [ColorEnum.BLUE, ColorEnum.WHITE],
  'black/natural ivory/asphalt grey': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.GREY],
  'lemon zest': [ColorEnum.YELLOW],
  'ice': [ColorEnum.BLUE],
  'black floral aop': [ColorEnum.BLACK, ColorEnum.PURPLE],
  'medium with paint': [ColorEnum.BROWN],
  'medium wash': [ColorEnum.BROWN],
  'barley': [ColorEnum.BEIGE],
  'coral stripe': [ColorEnum.PINK],
  'optic white/navy': [ColorEnum.WHITE, ColorEnum.NAVY],
  'שחור/אדום': [ColorEnum.BLACK, ColorEnum.RED],
  'faded olive multi stripe': [ColorEnum.GREEN],
  'crimson': [ColorEnum.RED],
  'peach dusk stripe': [ColorEnum.PINK],
  'שחור לורקס': [ColorEnum.RED],
  'רוז׳': [ColorEnum.RED],
  'צהוב פסטל': [ColorEnum.YELLOW],
  'פסים שחור': [ColorEnum.BLACK],
  'pink argyle': [ColorEnum.PINK],
  'lilac spring': [ColorEnum.PURPLE],
  'ג׳ייד': [ColorEnum.PURPLE],
  'blushing bride / balanced beige / brownie / bright white / black': [ColorEnum.PURPLE, ColorEnum.BEIGE, ColorEnum.BROWN, ColorEnum.WHITE, ColorEnum.BLACK],
  'white / navy / light pink': [ColorEnum.WHITE, ColorEnum.NAVY, ColorEnum.LIGHT_BLUE],
  'copen blue': [ColorEnum.BLUE],
  'light lilac': [ColorEnum.PURPLE],
  'שחור מט': [ColorEnum.BLACK],
  'rich grey': [ColorEnum.GREY],
  'tropical floral brilliant orange': [ColorEnum.PURPLE],
  'bright orange': [ColorEnum.ORANGE],
  'travertine': [ColorEnum.BEIGE],
  'mint rush': [ColorEnum.MINT],
  'sapphire red': [ColorEnum.PURPLE],
  'black acid wash': [ColorEnum.BLACK],
  'הדפס': [ColorEnum.BLACK],
  'washed tan': [ColorEnum.BEIGE],
  'olive strata': [ColorEnum.GREEN],
  'gold plated': [ColorEnum.GOLD],
  'blue plaid': [ColorEnum.BLUE],
  'butter yellow print': [ColorEnum.YELLOW],
  'tan plaid': [ColorEnum.BROWN],
  'רצועות': [ColorEnum.BLACK],
  'matt dark blue/matt black / gradient dark blue to grey': [ColorEnum.BLACK, ColorEnum.GREY],
  'wonder clay': [ColorEnum.BEIGE],
  'לבן 92': [ColorEnum.WHITE],
  'shadow red': [ColorEnum.RED],
  'rouge/optic white': [ColorEnum.RED, ColorEnum.WHITE],
  'פרחי': [ColorEnum.PURPLE],
  'פינסטרייפ': [ColorEnum.PURPLE],
  'glow blue': [ColorEnum.BLUE],
  'navy stripe': [ColorEnum.NAVY],
  'slate tie-dye': [ColorEnum.BLACK, ColorEnum.BLUE],
  'oat': [ColorEnum.BEIGE],
  'dark heather gray': [ColorEnum.BROWN],
  'blue haze pattern': [ColorEnum.BLUE],
  'bold aqua': [ColorEnum.BLUE],
  '10 cherry lush': [ColorEnum.BLACK],
  'light heather gray print': [ColorEnum.GREY],
  'black rins': [ColorEnum.BLACK],
  'blue burst': [ColorEnum.BLUE],
  'matt black- gold / gradient turquoise to transparent': [ColorEnum.BLACK, ColorEnum.GOLD, ColorEnum.BLUE],
  'dusty jade plaid': [ColorEnum.GREEN, ColorEnum.PURPLE],
  'sandalwood': [ColorEnum.BROWN],
  'strawberry field': [ColorEnum.PINK],
  'dark navy': [ColorEnum.NAVY],
  'ocean black to matt dark blue': [ColorEnum.BLUE, ColorEnum.BLACK],
  'optic white colorblock': [ColorEnum.WHITE],
  'optic white / multi stripe': [ColorEnum.WHITE, ColorEnum.MULTICOLOR],
  'נחש': [ColorEnum.BLACK],
  'tundra brown': [ColorEnum.BLACK],
  'preppy navy': [ColorEnum.BLUE],
  'cobalt': [ColorEnum.BLUE],
  'grey / black / heathered oat': [ColorEnum.GREY, ColorEnum.BLACK, ColorEnum.BEIGE],
  'sweet blue': [ColorEnum.BEIGE],
  'solar red': [ColorEnum.RED],
  'לבן + כחול': [ColorEnum.WHITE, ColorEnum.BLUE],
  'lime green': [ColorEnum.GREEN],
  'halo blue': [ColorEnum.BLUE],
  'navy blue and cream': [ColorEnum.NAVY, ColorEnum.BLUE],
  'blue moment': [ColorEnum.BLUE],
  'לילך מעושן': [ColorEnum.BLUE],
  'sheer oak/sour grape': [ColorEnum.BEIGE, ColorEnum.PURPLE],
  'minty essense stripe': [ColorEnum.MINT],
  'pink spark': [ColorEnum.PINK],
  'red / white / navy mini flag': [ColorEnum.RED, ColorEnum.WHITE, ColorEnum.BLUE],
  'cradle pink': [ColorEnum.PINK],
  'blue bird': [ColorEnum.BLUE],
  'evening blue': [ColorEnum.BLUE],
  'grey six': [ColorEnum.BLACK],
  'transparent dark brown / gradient dark orange to orange to light orange': [ColorEnum.BROWN, ColorEnum.ORANGE],
  'ancient white/navy': [ColorEnum.WHITE, ColorEnum.BLUE],
  'שטיפה בגוון ירוק': [ColorEnum.GREEN],
  'red logo': [ColorEnum.RED],
  'fossil grey': [ColorEnum.GREY],
  'stone stripe': [ColorEnum.BLACK],
  'brown beige blue demi': [ColorEnum.BROWN, ColorEnum.BEIGE, ColorEnum.BLUE],
  'cloud white / core black / cloud white': [ColorEnum.WHITE, ColorEnum.BLACK, ColorEnum.WHITE],
  'lavender frost': [ColorEnum.PURPLE],
  'teak': [ColorEnum.BROWN],
  'cream white': [ColorEnum.WHITE],
  'midnight': [ColorEnum.BLACK],
  'תכלת מלאנז\'': [ColorEnum.NAVY],
  '02_violet': [ColorEnum.PURPLE],
  'clear onix': [ColorEnum.BLACK],
  'bright white': [ColorEnum.WHITE],
  'safari canvas': [ColorEnum.GREEN],
  'light blue heather': [ColorEnum.LIGHT_BLUE],
  'dark mauve': [ColorEnum.PURPLE],
  'breezy blue stripe': [ColorEnum.BLUE],
  'dark gray': [ColorEnum.GREY],
  'פסים כחול': [ColorEnum.BLUE],
  'raw wht': [ColorEnum.WHITE],
  'ברונזה': [ColorEnum.BEIGE],
  'light grey melange': [ColorEnum.GREY],
  'shadow fig': [ColorEnum.BLACK],
  'crystal white': [ColorEnum.WHITE],
  'כתום בהיר': [ColorEnum.ORANGE],
  'quaker htr': [ColorEnum.BEIGE],
  'heather grey / balanced beige / black': [ColorEnum.GREY, ColorEnum.BEIGE, ColorEnum.WHITE],
  'medium pink': [ColorEnum.PURPLE],
  'לייט לבנדר': [ColorEnum.PURPLE],
  'tahiti berry': [ColorEnum.PURPLE],
  'breezy blue check': [ColorEnum.BLUE],
  'cream print': [ColorEnum.BEIGE],
  'clay': [ColorEnum.BROWN],
  '34 rose iris?': [ColorEnum.PURPLE],
  'emerald print': [ColorEnum.GREEN],
  'rouge': [ColorEnum.RED],
  'demi brown stripes / gardient dark grey brown to brown': [ColorEnum.BROWN, ColorEnum.GREY],
  'הדפסים': [ColorEnum.BLACK],
  'granite': [ColorEnum.GREY],
  'פרחוני מודפס': [ColorEnum.PURPLE],
  'rouge stripe': [ColorEnum.RED],
  'storm drk': [ColorEnum.BLACK],
  'פסים בצבע רוגע': [ColorEnum.PURPLE],
  'peach - 40': [ColorEnum.PINK],
  '19 runway rose': [ColorEnum.PURPLE],
  'בננה': [ColorEnum.ORANGE],
  'dark ripped wash': [ColorEnum.BROWN],
  'Ripped Denim': [ColorEnum.BROWN],
  'halo blush': [ColorEnum.PURPLE],
  'pink heather': [ColorEnum.PURPLE],
  'blue chime': [ColorEnum.BLUE],
  'f?te (fn)': [ColorEnum.PURPLE],
  'lipstick pink': [ColorEnum.PURPLE],
  'בורדו’': [ColorEnum.PURPLE],
  'ג׳ינס כחול': [ColorEnum.BLUE],
  'rouge/oat milk/black': [ColorEnum.RED, ColorEnum.BEIGE, ColorEnum.BLACK],
  'mesa': [ColorEnum.BROWN],
  'כחול נייבי': [ColorEnum.BLUE],
  'powder blue check': [ColorEnum.BLUE],
  'army green multi': [ColorEnum.GREEN],
  'misty blush': [ColorEnum.PURPLE],
  'semi green spark': [ColorEnum.GREEN],
  'ג\'ינס אינדיגו': [ColorEnum.GREEN],
  'transparent shiny dark burgundy / gradient dark blue to grey': [ColorEnum.BLACK, ColorEnum.PURPLE],
  'cloud white': [ColorEnum.WHITE],
  'desert sand / navy stripe': [ColorEnum.BEIGE, ColorEnum.BLUE],
  'blue haze': [ColorEnum.BLUE],
  'navy coney island': [ColorEnum.NAVY],
  'washed purple': [ColorEnum.PURPLE],
  'minty essence multi stripe': [ColorEnum.MINT],
  'heather ivory petal': [ColorEnum.BEIGE],
  'sunny orange multi': [ColorEnum.ORANGE],
  'spruce': [ColorEnum.GREEN],
  'cinnamon bark': [ColorEnum.BROWN],
  'uniform olive/optic white stripe': [ColorEnum.GREEN, ColorEnum.WHITE],
  'tinted light': [ColorEnum.BLUE],
  'demi havana / solid dark red brown': [ColorEnum.BEIGE, ColorEnum.RED],
  'preppy navy stripe': [ColorEnum.BLUE],
  'אוף-וויט': [ColorEnum.PURPLE],
  'frosted evergreen': [ColorEnum.BLACK],
  'blue stripe': [ColorEnum.BLUE],
  'breton dark night navy stripe': [ColorEnum.NAVY],
  'שעם': [ColorEnum.BLACK],
  'bonfire orange': [ColorEnum.BLACK],
  'transparent1': [ColorEnum.BLACK],
  'overdyed black': [ColorEnum.BLACK],
  'rose quartz stripe': [ColorEnum.PURPLE],
  'tommy navy': [ColorEnum.NAVY],
  'mid grey': [ColorEnum.GREY],
  'spring lime stripe': [ColorEnum.GREEN],
  'אלון': [ColorEnum.GREEN],
  'grey heather stripe': [ColorEnum.GREY],
  'gum': [ColorEnum.GREY],
  'לבן+זהב': [ColorEnum.WHITE, ColorEnum.GOLD],
  'deep green': [ColorEnum.GREEN],
  'dark cream': [ColorEnum.BEIGE],
  'lucid red': [ColorEnum.RED],
  'blue multi': [ColorEnum.BLUE],
  '1.4 bone': [],
  'silt beige tonal': [ColorEnum.BEIGE],
  'tannin': [ColorEnum.BROWN],
  'magic mauve': [ColorEnum.PURPLE],
  'light wash effect': [ColorEnum.PURPLE],
  'bliss': [ColorEnum.PURPLE],
  'precious pink/optic white stripe': [ColorEnum.PURPLE, ColorEnum.WHITE],
  'rich grey stripe': [ColorEnum.GREY],
  'blue print': [ColorEnum.BLUE],
  'rinse blue': [ColorEnum.BLUE],
  'clay strata': [ColorEnum.BROWN],
  'light pink/cash creme/fossil': [ColorEnum.PINK, ColorEnum.BEIGE, ColorEnum.WHITE],
  '11': [],
  'ערפל': [ColorEnum.BLACK],
  '60': [],
  'transparent taupe / gradient smoke to g15 to trans': [ColorEnum.BEIGE, ColorEnum.BLACK],
  'magic beige': [ColorEnum.BEIGE],
  'ורוד/לבן': [ColorEnum.PINK, ColorEnum.BLACK],
  'black_white': [ColorEnum.BLACK, ColorEnum.WHITE],
  'desert red': [ColorEnum.RED],
  'dusk blue': [ColorEnum.BLUE],
  'מינק': [ColorEnum.BLACK],
  'vapor': [ColorEnum.BLACK],
  'dark wash fade': [ColorEnum.BROWN],
  'vivid clover stripe': [ColorEnum.PURPLE],
  'mist stone': [ColorEnum.BEIGE],
  'miami aqua': [ColorEnum.BLUE],
  'medium rinse': [ColorEnum.BROWN],
  'שחור מודפס': [ColorEnum.BLACK],
  'לבן שחור': [ColorEnum.BLACK, ColorEnum.WHITE],
  'cloud white / core black / gold metallic': [ColorEnum.WHITE, ColorEnum.BLACK, ColorEnum.GOLD],
  'thorn': [ColorEnum.BLACK],
  'light wash': [ColorEnum.BLACK],
  'khaki sand': [ColorEnum.KHAKI],
  'red and navy blue': [ColorEnum.RED, ColorEnum.NAVY],
  'ג\'ינס': [ColorEnum.GREEN],
  'light beige heather stripe': [ColorEnum.BEIGE],
  'cherry red': [ColorEnum.RED],
  'אפור בהיר': [ColorEnum.BROWN],
  'medium cha': [ColorEnum.BROWN],
  'powder yellow': [ColorEnum.YELLOW],
  'black-white-red': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.RED],
  'מוס': [ColorEnum.BROWN],
  'cloudy blue / ecru stripe': [ColorEnum.BLUE, ColorEnum.BEIGE],
  'cryst cryst green': [ColorEnum.GREEN],
  'semi spark': [ColorEnum.PURPLE],
  'oatmeal print': [ColorEnum.BEIGE],
  'shiny gold / gradient dark brown/light brown': [ColorEnum.GOLD, ColorEnum.GREY],
  'n3 west coast': [ColorEnum.BLUE],
  'pink haze multi/butter cream': [ColorEnum.PURPLE, ColorEnum.WHITE],
  'light ripped wash': [ColorEnum.BROWN],
  'dusty jade': [ColorEnum.GREEN],
  'black / gradient light purple': [ColorEnum.BLACK, ColorEnum.LIGHT_BLUE],
  '4800b1': [ColorEnum.BLACK],
  'light_blue': [ColorEnum.BLUE],
  'oatmeal heather stripe': [ColorEnum.BEIGE],
  'יין פסים': [ColorEnum.YELLOW],
  'שחור ווש': [ColorEnum.BLACK],
  'פרחים': [ColorEnum.PURPLE],
  'קובלט': [ColorEnum.BLUE],
  'transparent taupe / gradient smoke to beige': [ColorEnum.BEIGE, ColorEnum.BLACK],
  'navy / blue': [ColorEnum.NAVY, ColorEnum.BLUE],
  'pastel purple': [ColorEnum.PURPLE],
  'icy pink multi': [ColorEnum.PURPLE, ColorEnum.PINK],
  'washed cherry': [ColorEnum.RED],
  'blue_white': [ColorEnum.BLUE, ColorEnum.WHITE],
  'dark khaki': [ColorEnum.BROWN],
  'light powdery blue': [ColorEnum.BLUE],
  'blue dawn': [ColorEnum.BLUE],
  'limestone': [ColorEnum.BEIGE],
  '04 pussy cat': [],
  'flash aqua': [ColorEnum.BLUE],
  'pewter grey': [ColorEnum.GREY],
  'wonder beige': [ColorEnum.BEIGE],
  'aurora ink': [ColorEnum.PURPLE],
  'grey blue': [ColorEnum.GREY],
  'putty': [ColorEnum.BLACK],
  'navy blue plaid': [ColorEnum.NAVY],
  'koi': [ColorEnum.BLUE],
  'khalel': [ColorEnum.BLACK],
  'powder blue plaid': [ColorEnum.BLUE, ColorEnum.WHITE],
  'ancient white': [ColorEnum.WHITE],
  'october grey': [ColorEnum.BLACK],
  'ultra blue': [ColorEnum.BLUE],
  'sage stripe': [ColorEnum.GREEN],
  'סגול בהיר': [ColorEnum.PURPLE],
  'shiny light gold/black/gradient smoke': [ColorEnum.GOLD, ColorEnum.BLACK, ColorEnum.GREY],
  'לבן ברבור': [ColorEnum.WHITE],
  'rhino grey': [ColorEnum.GREY],
  'black floral': [ColorEnum.PURPLE],
  'baller': [ColorEnum.BLACK],
  'preppy navy heather': [ColorEnum.BLUE, ColorEnum.PURPLE],
  'navy multi': [ColorEnum.NAVY],
  'גרייג׳': [ColorEnum.PURPLE],
  'white and pink floral': [ColorEnum.WHITE, ColorEnum.PURPLE],
  
  // Additional missing color mappings
  'אופוויט מלאנז\'': [ColorEnum.OFFWHITE],
  'dark brown\t': [ColorEnum.BROWN],
  'לילך בהיר': [ColorEnum.LILAC],
  'אוף ווייט': [ColorEnum.OFFWHITE],
  'Mustard': [ColorEnum.MUSTARD],
  'dark cream and cream': [ColorEnum.CREAM],
  'beechwood': [ColorEnum.BROWN],
  'shiny black': [ColorEnum.BLACK],
  'brown camo': [ColorEnum.BROWN, ColorEnum.CAMOUFLAGE],
  'פודרה': [ColorEnum.PINK],
  'grey wash': [ColorEnum.GREY],
  'ורוד פלמינגו': [ColorEnum.PINK],
  'תכלת מלאנז\'\'': [ColorEnum.NAVY],
  'נייבי מלאנז\'': [ColorEnum.NAVY],
  'כחלחל': [ColorEnum.BLUE],
  'gold / gradient smoke to blue to orange': [ColorEnum.GOLD, ColorEnum.BLUE, ColorEnum.ORANGE],
  'vintage rosy': [ColorEnum.PINK],
  'black plaid': [ColorEnum.BLACK, ColorEnum.PLAID],
  'beige heather stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'dark green stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'black stripe': [ColorEnum.BLACK, ColorEnum.STRIPED],
  'ורוד פוקסיה': [ColorEnum.PINK],
  'marocain': [ColorEnum.BROWN],
  'precious pink / optic white stripe': [ColorEnum.PINK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'white/red': [ColorEnum.WHITE, ColorEnum.RED],
  'green spark': [ColorEnum.GREEN],
  'brisk blue': [ColorEnum.BLUE],
  'dusk blue floral': [ColorEnum.BLUE, ColorEnum.FLORAL],
  'flora pink heather': [ColorEnum.PINK],
  'rainforest green': [ColorEnum.GREEN],
  'dark brown camo': [ColorEnum.BROWN, ColorEnum.CAMOUFLAGE],
  'bank blue': [ColorEnum.BLUE],
  'blue moment stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'pixel rainbow club blue multi': [ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'talc': [ColorEnum.WHITE],
  'shiny rose gold/taupe-nude-trans taupe': [ColorEnum.GOLD, ColorEnum.TAUPE],
  'terra pink': [ColorEnum.PINK],
  'black-gold/gradient brown': [ColorEnum.BLACK, ColorEnum.GOLD, ColorEnum.BROWN],
  'tahiti berry check': [ColorEnum.PURPLE, ColorEnum.CHECKED],
  'בלאש': [ColorEnum.PINK],
  'trans light grey': [ColorEnum.GREY, ColorEnum.TRANSPARENT],
  'אנטרציט': [ColorEnum.BLACK],
  'peacoat': [ColorEnum.NAVY],
  'primary red / white stripe': [ColorEnum.RED, ColorEnum.WHITE, ColorEnum.STRIPED],
  '16 scarlet rouge': [ColorEnum.RED],
  'beech white/antique white/antique white': [ColorEnum.WHITE],
  'breton small brilliant orange': [ColorEnum.ORANGE],
  'Royal Blue': [ColorEnum.ROYAL_BLUE],
  'onix': [ColorEnum.BLACK],
  'trench stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'light brown plaid': [ColorEnum.BROWN, ColorEnum.PLAID],
  'טופו': [ColorEnum.WHITE],
  'preloved scarlet': [ColorEnum.RED],
  'white -crystal stones': [ColorEnum.WHITE],
  'storm': [ColorEnum.GREY],
  'sanguine m': [ColorEnum.RED],
  '123 devoted': [ColorEnum.RED],
  'פוקסיה': [ColorEnum.PINK],
  'ballet pink/white': [ColorEnum.PINK, ColorEnum.WHITE],
  'garden rose': [ColorEnum.PINK],
  'frosted green': [ColorEnum.GREEN],
  'semi lucid blue': [ColorEnum.BLUE],
  'medium destroy': [ColorEnum.BROWN],
  'colorado blue': [ColorEnum.BLUE],
  'שמיים בהירים.': [ColorEnum.SKY_BLUE],
  'light lilac floral': [ColorEnum.LILAC, ColorEnum.FLORAL],
  'shiny gold / gradient dark orange to orange to light orange': [ColorEnum.GOLD, ColorEnum.ORANGE],
  'medium faded': [ColorEnum.GREY],
  'fresh white stripe': [ColorEnum.WHITE, ColorEnum.STRIPED],
  'matt dark gun / gradient smoke to dark turquoise to trans': [ColorEnum.BLACK, ColorEnum.TURQUOISE],
  'dark blue floral': [ColorEnum.DARK_BLUE, ColorEnum.FLORAL],
  'blue spell stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  '05': [],
  'דלעת': [ColorEnum.ORANGE],
  'ophelia purple': [ColorEnum.PURPLE],
  'ripped light wash': [ColorEnum.BEIGE],
  'pistachio': [ColorEnum.GREEN],
  'charcoal melang': [ColorEnum.CHARCOAL],
  'marbel black-pink-turrquoise': [ColorEnum.BLACK, ColorEnum.PINK, ColorEnum.TURQUOISE],
  'beige heather multi': [ColorEnum.BEIGE, ColorEnum.MULTICOLOR],
  'navy dd': [ColorEnum.NAVY],
  'pool party': [ColorEnum.GREEN],
  'pulse lime': [ColorEnum.GREEN],
  'lavender frost/college purple': [ColorEnum.LAVENDER, ColorEnum.PURPLE],
  'sea': [ColorEnum.BLUE],
  'charcoal locket print': [ColorEnum.CHARCOAL],
  'club blue': [ColorEnum.BLUE],
  'כתום ניאון': [ColorEnum.ORANGE],
  'acid orange': [ColorEnum.ORANGE],
  'stone khaki': [ColorEnum.KHAKI],
  'wonder blue': [ColorEnum.BLUE],
  'core black / cloud white / core black': [ColorEnum.BLACK, ColorEnum.WHITE],
  'hot coco': [ColorEnum.BROWN],
  'optic white denim': [ColorEnum.WHITE, ColorEnum.DENIM],
  '15 wild ginger': [ColorEnum.ORANGE],
  'trans green': [ColorEnum.GREEN, ColorEnum.TRANSPARENT],
  'כחול פטרול': [ColorEnum.BLUE],
  'chocolate': [ColorEnum.BROWN],
  
  // Additional color mappings
  'brown print': [ColorEnum.BROWN],
  'deep rouge': [ColorEnum.RED],
  'grey stripe': [ColorEnum.GREY, ColorEnum.STRIPED],
  'cloud white floral': [ColorEnum.WHITE, ColorEnum.FLORAL],
  'אוקיינוס': [ColorEnum.BLUE],
  'rouge multi': [ColorEnum.RED, ColorEnum.MULTICOLOR],
  'חום שוקו': [ColorEnum.BROWN],
  'סגול כהה': [ColorEnum.PURPLE],
  'breezy blue/white': [ColorEnum.BLUE, ColorEnum.WHITE],
  'keepsake blue': [ColorEnum.BLUE],
  'shiny gold / gradient light green to trans': [ColorEnum.GOLD, ColorEnum.GREEN],
  'ורוד בייבי ': [ColorEnum.BABY_PINK],
  'blue wave': [ColorEnum.BLUE],
  'shiny black/shiny gold': [ColorEnum.BLACK, ColorEnum.GOLD],
  'gold / gradient smoke': [ColorEnum.GOLD],
  'heather gray': [ColorEnum.GREY],
  'טראפל': [ColorEnum.BROWN],
  'black / multi': [ColorEnum.BLACK, ColorEnum.MULTICOLOR],
  'navy blue stripe': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'starch blue': [ColorEnum.BLUE],
  'light grey heather / black / heathered oat': [ColorEnum.GREY, ColorEnum.BLACK, ColorEnum.BEIGE],
  'ivory/gravel': [ColorEnum.IVORY, ColorEnum.GREY],
  'נייבי כהה': [ColorEnum.NAVY],
  'coffee bean': [ColorEnum.BROWN],
  'red / white / blue': [ColorEnum.RED, ColorEnum.WHITE, ColorEnum.BLUE],
  'pistache m': [ColorEnum.GREEN],
  'solar blue': [ColorEnum.BLUE],
  'ivory / multi': [ColorEnum.IVORY, ColorEnum.MULTICOLOR],
  'טורקיז בהיר': [ColorEnum.TURQUOISE],
  'camo print': [ColorEnum.CAMOUFLAGE],
  'מפוספס': [ColorEnum.STRIPED],
  'מונסון': [ColorEnum.BLUE],
  'taupe-nude-trans taupe': [ColorEnum.TAUPE, ColorEnum.NUDE],
  'blue grey': [ColorEnum.BLUE, ColorEnum.GREY],
  'passionate': [ColorEnum.RED],
  'almost yellow': [ColorEnum.YELLOW],
  '1.3 nude ivory': [ColorEnum.NUDE, ColorEnum.IVORY],
  '2.7 vellum': [ColorEnum.BEIGE],
  'light beige': [ColorEnum.BEIGE],
  'bold red/dark bold red': [ColorEnum.RED],
  'intensity 1': [ColorEnum.RED],
  '3.7 champagne': [ColorEnum.BRONZE],
  'navy/white': [ColorEnum.NAVY, ColorEnum.WHITE],
  'red / small flowers': [ColorEnum.RED, ColorEnum.FLORAL],
  'light gray camo': [ColorEnum.GREY, ColorEnum.CAMOUFLAGE],
  'cerise': [ColorEnum.PINK],
  'black/light ivory/starch blue/jumie stripe white vapor/goodnight plum': [ColorEnum.BLACK, ColorEnum.IVORY, ColorEnum.BLUE, ColorEnum.WHITE],
  'beige stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'navy/red': [ColorEnum.NAVY, ColorEnum.RED],
  'dusty blue floral': [ColorEnum.BLUE, ColorEnum.FLORAL],
  'black/white': [ColorEnum.BLACK, ColorEnum.WHITE],
  'dark grey carpenter': [ColorEnum.GREY],
  'smoky blue': [ColorEnum.BLUE],
  'taupe stripe': [ColorEnum.TAUPE, ColorEnum.STRIPED],
  'dark ripped': [ColorEnum.BROWN],
  'ורוד כהה': [ColorEnum.PINK],
  'gold / gradient dark orange to orange to light orange': [ColorEnum.GOLD, ColorEnum.ORANGE],
  'crimson check': [ColorEnum.RED, ColorEnum.CHECKED],
  'whimsy pink stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'gold- black / gradient brown': [ColorEnum.GOLD, ColorEnum.BLACK, ColorEnum.BROWN],
  'trans dark burgundy / gradient brown': [ColorEnum.BORDEAUX, ColorEnum.BROWN],
  '130 rose dusk (fn)': [ColorEnum.PINK],
  'dark emerald': [ColorEnum.GREEN],
  'port': [ColorEnum.BORDEAUX],
  'taupetastic': [ColorEnum.TAUPE],
  'vessel blue': [ColorEnum.BLUE],
  'matt dark trans blue': [ColorEnum.BLUE, ColorEnum.TRANSPARENT],
  'white/club blue': [ColorEnum.WHITE, ColorEnum.BLUE],
  'citronella floral': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'toasted almond': [ColorEnum.BROWN],
  'grey one': [ColorEnum.GREY],
  'orbit grey': [ColorEnum.GREY],
  '05 - sundrunk': [ColorEnum.ORANGE],
  'dark magma': [ColorEnum.RED],
  'sandalwood/cloudy blue heather stripe': [ColorEnum.BROWN, ColorEnum.BLUE, ColorEnum.STRIPED],
  'gray plaid': [ColorEnum.GREY, ColorEnum.PLAID],
  'ורוד מעושן': [ColorEnum.PINK],
  'white/blue pattern': [ColorEnum.WHITE, ColorEnum.BLUE],
  'light gray': [ColorEnum.GREY],
  'buttercream stripe': [ColorEnum.CREAM, ColorEnum.STRIPED],
  'aruba green': [ColorEnum.GREEN],
  'light medium': [ColorEnum.BEIGE],
  'matt black- gold': [ColorEnum.BLACK, ColorEnum.GOLD],
  'medium light wash': [ColorEnum.BEIGE],
  'חום-כחול': [ColorEnum.BROWN, ColorEnum.BLUE],
  'הדפסה': [ColorEnum.BLACK],
  'beige / orange stripe': [ColorEnum.BEIGE, ColorEnum.ORANGE, ColorEnum.STRIPED],
  'ivory petal/navy stripe': [ColorEnum.IVORY, ColorEnum.NAVY, ColorEnum.STRIPED],
  'black/gradient brown vg-31a': [ColorEnum.BLACK, ColorEnum.BROWN],
  'hi-res yellow': [ColorEnum.YELLOW],
  'carbon': [ColorEnum.BLACK],
  'primary red multi': [ColorEnum.RED, ColorEnum.MULTICOLOR],
  'shiny light gold/shiny black/gradient brown vg-31a': [ColorEnum.GOLD, ColorEnum.BLACK, ColorEnum.BROWN],
  'signal orange': [ColorEnum.ORANGE],
  'aqua night': [ColorEnum.BLUE],
  'mudstone denim': [ColorEnum.BROWN, ColorEnum.DENIM],
  'black / solid dirty brown': [ColorEnum.BLACK, ColorEnum.BROWN],
  'dark': [ColorEnum.BLACK],
  'classic pink stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'wedge blue/white stripe': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.STRIPED],
  
  // Additional color mappings
  'seldom blue / optic white stripe': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.STRIPED],
  'frosted evergreen/blue multi': [ColorEnum.GREEN, ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'heather brown': [ColorEnum.BROWN],
  'בגוון ג\'ינס': [ColorEnum.DENIM],
  'ורוד מעושן בהיר': [ColorEnum.PINK],
  '108 headline': [ColorEnum.BLACK],
  'preloved ink': [ColorEnum.BLUE],
  'two tone gold/silver': [ColorEnum.GOLD, ColorEnum.SILVER],
  'black-gold / gradient dark brown to orange to trans': [ColorEnum.BLACK, ColorEnum.GOLD, ColorEnum.BROWN, ColorEnum.ORANGE],
  'cognac': [ColorEnum.BROWN],
  'green stone': [ColorEnum.GREEN],
  'black with crystal stones': [ColorEnum.BLACK],
  'טאופ כהה': [ColorEnum.TAUPE],
  'battle green/white': [ColorEnum.GREEN, ColorEnum.WHITE],
  'n2 dolce': [ColorEnum.BLACK],
  'לבן\\שחור': [ColorEnum.WHITE, ColorEnum.BLACK],
  'capri blue': [ColorEnum.BLUE],
  'pink peony': [ColorEnum.PINK],
  'camo': [ColorEnum.CAMOUFLAGE],
  'wonder taupe': [ColorEnum.TAUPE],
  'classic pink': [ColorEnum.PINK],
  'big chill blue': [ColorEnum.BLUE],
  'tan print': [ColorEnum.TAN],
  'ורוד פודרה': [ColorEnum.PINK],
  'violet tone': [ColorEnum.PURPLE],
  'cornflower blue': [ColorEnum.BLUE],
  'platinum olive': [ColorEnum.OLIVE],
  'milky way': [ColorEnum.WHITE],
  'shiny dark gun': [ColorEnum.BLACK],
  'מולטי 1': [ColorEnum.MULTICOLOR],
  'shadow green': [ColorEnum.GREEN],
  'trout': [ColorEnum.BROWN],
  'navy blue check': [ColorEnum.NAVY, ColorEnum.CHECKED],
  'blue pattern': [ColorEnum.BLUE],
  'black/silver drop': [ColorEnum.BLACK, ColorEnum.SILVER],
  'black-gold': [ColorEnum.BLACK, ColorEnum.GOLD],
  'evergreen': [ColorEnum.GREEN],
  'matt demi': [ColorEnum.GREY],
  'newsprint': [ColorEnum.GREY],
  '511 steel magnolia': [ColorEnum.GREY],
  'citronella': [ColorEnum.GREEN],
  'breezy blue/ivory petal mouline': [ColorEnum.BLUE, ColorEnum.IVORY],
  'spiced chai': [ColorEnum.BROWN],
  'ווש': [ColorEnum.BLUE],
  'dazzling blue': [ColorEnum.BLUE],
  'ורוד בהיר.': [ColorEnum.PINK],
  'blue fusion': [ColorEnum.BLUE],
  'light ripped': [ColorEnum.BEIGE],
  'solar grey': [ColorEnum.GREY],
  'light wash denim': [ColorEnum.LIGHT_DENIM],
  'party on': [ColorEnum.MULTICOLOR],
  '2n0 creme': [ColorEnum.CREAM],
  'peach dusk': [ColorEnum.PINK],
  'light navy': [ColorEnum.NAVY],
  'soft cream denim': [ColorEnum.CREAM, ColorEnum.DENIM],
  'light green stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'black-transparent olive': [ColorEnum.BLACK, ColorEnum.OLIVE, ColorEnum.TRANSPARENT],
  'gray dawn / bright white / forever blue / balanced beige / blushing bride': [ColorEnum.GREY, ColorEnum.WHITE, ColorEnum.BLUE, ColorEnum.BEIGE, ColorEnum.PINK],
  'gold metallic': [ColorEnum.GOLD, ColorEnum.METALLIC],
  'Bronze': [ColorEnum.BRONZE],
  'ivory silk': [ColorEnum.IVORY],
  'raspberry': [ColorEnum.PINK],
  'cloud white pattern': [ColorEnum.WHITE],
  'glory grey mel': [ColorEnum.GREY],
  'heather black': [ColorEnum.BLACK],
  'טרקוטה': [ColorEnum.RED],
  'carnival pink': [ColorEnum.PINK],
  '159 - solaire': [ColorEnum.YELLOW],
  'deep crimson fruit': [ColorEnum.RED],
  'שחור סלאב': [ColorEnum.BLACK],
  'פסים צבעוני': [ColorEnum.STRIPED, ColorEnum.MULTICOLOR],
  'לבן פרחוני': [ColorEnum.WHITE, ColorEnum.FLORAL],
  'washed tahiti berry': [ColorEnum.PURPLE],
  'dark grey': [ColorEnum.GREY],
  'golden champagne / gradient smoke to beige': [ColorEnum.BRONZE, ColorEnum.BEIGE],
  'drk satura': [ColorEnum.BLACK],
  'washed black dd': [ColorEnum.BLACK],
  'פסים ירוק': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'light green camo': [ColorEnum.GREEN, ColorEnum.CAMOUFLAGE],
  'collegiate navy': [ColorEnum.NAVY],
  'light taupe': [ColorEnum.TAUPE],
  'demi / gradient light green to trans': [ColorEnum.GREEN],
  'גינס בהיר': [ColorEnum.LIGHT_DENIM],
  'לבנדר אקליפטוס': [ColorEnum.LAVENDER, ColorEnum.GREEN],
  'frosted evergreen/optic white': [ColorEnum.GREEN, ColorEnum.WHITE],
  'bliss pink': [ColorEnum.PINK],
  'fresh white': [ColorEnum.WHITE],
  'silver2': [ColorEnum.SILVER],
  'ורוד  מעושן': [ColorEnum.PINK],
  'warm sandstone': [ColorEnum.BEIGE],
  '100 100': [ColorEnum.BLACK],
  'warm grey': [ColorEnum.GREY],
  'desert sand stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'primary red': [ColorEnum.RED],
  'shiny light gold/shiny trasn l.champagne / gradient smoke to beige': [ColorEnum.GOLD, ColorEnum.BRONZE, ColorEnum.BEIGE],
  'choclate': [ColorEnum.BROWN],
  'dusty blue stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'דנים לא שטוף': [ColorEnum.DENIM],
  'liquid soap': [ColorEnum.WHITE],
  'trench': [ColorEnum.BEIGE],
  
  // Additional color mappings
  'eucalyptus green': [ColorEnum.GREEN],
  'navy colorblock': [ColorEnum.NAVY],
  'beige heather multi stripe': [ColorEnum.BEIGE, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'rose gold with crystal stones / gradient dark smoke brown to brown orange to trans': [ColorEnum.GOLD, ColorEnum.BROWN, ColorEnum.ORANGE],
  '1.1 warm sand': [ColorEnum.BEIGE],
  'xxxxx813': [ColorEnum.BLACK],
  'ash purple': [ColorEnum.PURPLE],
  'crimson plaid': [ColorEnum.RED, ColorEnum.PLAID],
  'בז\'\'': [ColorEnum.BEIGE],
  'חמאה': [ColorEnum.YELLOW],
  'chestnut': [ColorEnum.BROWN],
  'demi leo': [ColorEnum.ORANGE],
  'matt transparent dark brown / gradient turquoise to transparent': [ColorEnum.BROWN, ColorEnum.TURQUOISE],
  '03 casablanca': [ColorEnum.BEIGE],
  '121 lark': [ColorEnum.BROWN],
  'tangerine': [ColorEnum.ORANGE],
  'night': [ColorEnum.BLACK],
  'matt black-shiny gold': [ColorEnum.BLACK, ColorEnum.GOLD],
  'גוף': [ColorEnum.NUDE],
  'cocoa': [ColorEnum.BROWN],
  'ג׳ינס פסים': [ColorEnum.DENIM, ColorEnum.STRIPED],
  'vapour pink': [ColorEnum.PINK],
  'breton small dark night navy': [ColorEnum.NAVY],
  'bahia light blue': [ColorEnum.LIGHT_BLUE],
  'נייבי פסים': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'bright blue': [ColorEnum.BLUE],
  'legacy brown heather': [ColorEnum.BROWN],
  'provence': [ColorEnum.PURPLE],
  'shiny gold/shiny black / gradient brown vg-31a': [ColorEnum.GOLD, ColorEnum.BLACK, ColorEnum.BROWN],
  'off white - rose quartz': [ColorEnum.OFFWHITE, ColorEnum.PINK],
  'וניל': [ColorEnum.WHITE],
  'medium red': [ColorEnum.RED],
  'platinum olive stripe': [ColorEnum.OLIVE, ColorEnum.STRIPED],
  'crystal clear blue/white': [ColorEnum.BLUE, ColorEnum.WHITE],
  'שחור + לבן': [ColorEnum.BLACK, ColorEnum.WHITE],
  'powder blue': [ColorEnum.BLUE],
  'ecru multi stripe': [ColorEnum.BEIGE, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'flag critter navy': [ColorEnum.NAVY],
  'תכלת אסיד': [ColorEnum.TURQUOISE],
  'light vapor': [ColorEnum.WHITE],
  'classic pink/white stripe': [ColorEnum.PINK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'twilight rose': [ColorEnum.PINK],
  'anchor blue': [ColorEnum.BLUE],
  'navy plaid': [ColorEnum.NAVY, ColorEnum.PLAID],
  'white with pink floral': [ColorEnum.WHITE, ColorEnum.PINK, ColorEnum.FLORAL],
  'washed black': [ColorEnum.BLACK],
  'crystal sand': [ColorEnum.BEIGE],
  'army green': [ColorEnum.GREEN],
  'dusty lavender': [ColorEnum.LAVENDER],
  'silver birch': [ColorEnum.SILVER],
  'תכלת בהיר': [ColorEnum.TURQUOISE],
  'light heather grey': [ColorEnum.GREY],
  'lava': [ColorEnum.RED],
  'fire red stripe': [ColorEnum.RED, ColorEnum.STRIPED],
  'red / cream check': [ColorEnum.RED, ColorEnum.CREAM, ColorEnum.CHECKED],
  'trans light light peach': [ColorEnum.PINK, ColorEnum.TRANSPARENT],
  'white with blue floral': [ColorEnum.WHITE, ColorEnum.BLUE, ColorEnum.FLORAL],
  'orbiter': [ColorEnum.BLUE],
  'pacific': [ColorEnum.BLUE],
  'light medium wash': [ColorEnum.BEIGE],
  'icy pink stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'precious pink': [ColorEnum.PINK],
  '122 smitten': [ColorEnum.PINK],
  'desert sand': [ColorEnum.BEIGE],
  'celadon green': [ColorEnum.GREEN],
  'silt beige': [ColorEnum.BEIGE],
  'blue floral': [ColorEnum.BLUE, ColorEnum.FLORAL],
  'pink heather stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'light olive green camo': [ColorEnum.GREEN, ColorEnum.CAMOUFLAGE],
  'true navy': [ColorEnum.NAVY],
  'שמנת': [ColorEnum.CREAM],
  'בז\' פסים': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'dark red/dark red': [ColorEnum.RED],
  'sandalwood/ivory petal mouline': [ColorEnum.BROWN, ColorEnum.IVORY],
  'glamour pink': [ColorEnum.PINK],
  'grey whisper': [ColorEnum.GREY],
  'דרך כחולה': [ColorEnum.BLUE],
  'aurora black': [ColorEnum.BLACK],
  'undertone black multi': [ColorEnum.BLACK, ColorEnum.MULTICOLOR],
  'classic white': [ColorEnum.WHITE],
  'obsidian': [ColorEnum.BLACK],
  'vessel blue multi stripe': [ColorEnum.BLUE, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  '133 scarlet stiletto': [ColorEnum.RED],
  'black-white stripe': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'light blue stripe': [ColorEnum.LIGHT_BLUE, ColorEnum.STRIPED],
  'semi blue burst': [ColorEnum.BLUE],
  'light heather  grey': [ColorEnum.GREY],
  'transparent dark brown': [ColorEnum.BROWN, ColorEnum.TRANSPARENT],
  'dove grey heather': [ColorEnum.GREY],
  'rustic clay': [ColorEnum.BROWN],
  'moss': [ColorEnum.GREEN],
  'black and white stripe': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'butter yellow floral': [ColorEnum.YELLOW, ColorEnum.FLORAL],
  'magenta smoke': [ColorEnum.PINK],
  '03 nubile': [],
  'frost': [ColorEnum.WHITE],
  'rose quartz': [ColorEnum.PINK],
  'מולטי 3': [ColorEnum.MULTICOLOR],
  'grey green': [ColorEnum.GREY, ColorEnum.GREEN],
  'black- white- blue': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.BLUE],
  
  // Additional color mappings
  'trans dark burgundy': [ColorEnum.BORDEAUX],
  'light navy heather': [ColorEnum.NAVY],
  'חום/לבן': [ColorEnum.BROWN, ColorEnum.WHITE],
  'חרדל בהיר': [ColorEnum.MUSTARD],
  'sesame': [ColorEnum.BEIGE],
  'brown green demi': [ColorEnum.BROWN, ColorEnum.GREEN],
  'אספרסו': [ColorEnum.BROWN],
  'shadow brown': [ColorEnum.BROWN],
  'light heather oatmeal': [ColorEnum.BEIGE],
  'בז\'\' בהיר/שחור': [ColorEnum.BEIGE, ColorEnum.BLACK],
  'harvest wheat': [ColorEnum.BEIGE],
  'white/nova white/aero blue': [ColorEnum.WHITE, ColorEnum.BLUE],
  'dark wash denim': [ColorEnum.DENIM],
  'romantic blue': [ColorEnum.BLUE],
  'white dot': [ColorEnum.WHITE],
  'fandango pink multi stripe': [ColorEnum.PINK, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'military denim': [ColorEnum.DENIM],
  'lilac spring heather': [ColorEnum.LILAC],
  'light grey print': [ColorEnum.GREY],
  'deeper': [ColorEnum.BLUE],
  'coral fusion': [ColorEnum.ORANGE],
  'dusty purple': [ColorEnum.PURPLE],
  'lucid blue': [ColorEnum.BLUE],
  'PURPLE PAISLEY': [ColorEnum.PURPLE],
  'marlin': [ColorEnum.BLUE],
  'light brown grey': [ColorEnum.BROWN, ColorEnum.GREY],
  'light heather brown': [ColorEnum.BROWN],
  'pure ruby': [ColorEnum.RED],
  'ecru / brilliant orange fine stripe': [ColorEnum.BEIGE, ColorEnum.ORANGE, ColorEnum.STRIPED],
  'spring lime': [ColorEnum.GREEN],
  'matt bottle olive-matt dark gun': [ColorEnum.GREEN],
  'פסים': [ColorEnum.STRIPED],
  'faded black': [ColorEnum.BLACK],
  'balanced beige': [ColorEnum.BEIGE],
  'faded chambray blue': [ColorEnum.BLUE],
  'סלדין': [ColorEnum.GREEN],
  'berber': [ColorEnum.BEIGE],
  'demi leo / gradient brown': [ColorEnum.ORANGE, ColorEnum.BROWN],
  'goodnight plum': [ColorEnum.PURPLE],
  'iron metallic': [ColorEnum.GREY],
  'מרווה כהה': [ColorEnum.GREEN],
  'night blue': [ColorEnum.NAVY],
  'country ivory': [ColorEnum.WHITE],
  'olive green camo': [ColorEnum.GREEN, ColorEnum.CAMOUFLAGE],
  'faded medium wash denim': [ColorEnum.DENIM],
  'black/gradient smoke': [ColorEnum.BLACK],
  '40 rose beam': [ColorEnum.PINK],
  'ecru stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'washed dark gray': [ColorEnum.GREY],
  'fandango pink multi': [ColorEnum.PINK, ColorEnum.MULTICOLOR],
  'shiny black / solid mustard brown': [ColorEnum.BLACK, ColorEnum.BROWN],
  'silver1': [ColorEnum.SILVER],
  'preppy navy/white': [ColorEnum.NAVY, ColorEnum.WHITE],
  '3w1 golden': [ColorEnum.GOLD],
  'minty essence stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'lead': [ColorEnum.GREY],
  'platinum metallic': [ColorEnum.SILVER],
  'white pattern': [ColorEnum.WHITE],
  'harbor cove': [ColorEnum.BLUE],
  'dark red': [ColorEnum.RED],
  'charcoal heather gray': [ColorEnum.GREY],
  'זברה': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'light destroy': [ColorEnum.GREY],
  'light blue print': [ColorEnum.BLUE],
  'heather tan': [ColorEnum.BEIGE],
  'raspberry coulis': [ColorEnum.PINK],
  'clear pink': [ColorEnum.PINK],
  'dark ash': [ColorEnum.GREY],
  'mufc red': [ColorEnum.RED],
  'pink peony stripe': [ColorEnum.PINK, ColorEnum.STRIPED],
  'golden rays': [ColorEnum.GOLD],
  'matt black - matt dark gun / smoke to blue': [ColorEnum.BLACK, ColorEnum.BLUE],
  'olive green floral': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'ג\'ינס וינטאג\'': [ColorEnum.DENIM],
  'חקי': [ColorEnum.GREEN],
  'פסים ורוד': [ColorEnum.PINK, ColorEnum.STRIPED],
  'white / mini stripe paisley': [ColorEnum.WHITE],
  'purple grey': [ColorEnum.PURPLE, ColorEnum.GREY],
  'tea biscuit multi': [ColorEnum.BEIGE, ColorEnum.MULTICOLOR],
  'space blue': [ColorEnum.BLUE],
  'guava': [ColorEnum.PINK],
  '7.5 shell beige': [ColorEnum.BEIGE],
  'beige/navy stripe': [ColorEnum.BEIGE, ColorEnum.NAVY, ColorEnum.STRIPED],
  'vivid clover': [ColorEnum.GREEN],
  'dark red floral': [ColorEnum.RED, ColorEnum.FLORAL],
  'dark blue wash denim': [ColorEnum.DENIM],
  'שמיים בהירים': [ColorEnum.BLUE],
  'dark pink': [ColorEnum.PINK],
  'magic lilac': [ColorEnum.LILAC],
  'charcoal green tonal': [ColorEnum.GREEN],
  'linen green': [ColorEnum.GREEN],
  'authentic grey': [ColorEnum.GREY],
  'light wash chambray': [ColorEnum.BLUE],
  'alumina': [ColorEnum.GREY],
  'demi havana / gradient dark orange to orange to light orange': [ColorEnum.BROWN, ColorEnum.ORANGE],
  'almost pink': [ColorEnum.PINK],
  'מיד כחול': [ColorEnum.BLUE],
  'light khaki': [ColorEnum.GREEN],
  'ecru/carbon navy stripe': [ColorEnum.BEIGE, ColorEnum.NAVY, ColorEnum.STRIPED],
  'tactile blue': [ColorEnum.BLUE],
  
  // Additional color mappings
  'black light yellow demi': [ColorEnum.BLACK, ColorEnum.YELLOW],
  'dark grey heather': [ColorEnum.GREY],
  'brilliant orange stripe': [ColorEnum.ORANGE, ColorEnum.STRIPED],
  'light heather mocha': [ColorEnum.MOCHA],
  'primary red stripe': [ColorEnum.RED, ColorEnum.STRIPED],
  'battle green': [ColorEnum.GREEN],
  'heather light grey': [ColorEnum.GREY],
  'faded indigo': [ColorEnum.INDIGO],
  'semi lucid red': [ColorEnum.RED],
  'צהוב בננה': [ColorEnum.YELLOW],
  'light pink multi stripe': [ColorEnum.PINK, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'matt brown / gradient turquoise to transparent': [ColorEnum.BROWN, ColorEnum.TURQUOISE],
  'blue coal': [ColorEnum.BLUE],
  'נמר': [ColorEnum.LEOPARD],
  'buttercream': [ColorEnum.YELLOW],
  'ג׳ינס כהה': [ColorEnum.DENIM],
  'grey five': [ColorEnum.GREY],
  'real blue': [ColorEnum.BLUE],
  'white yellow stripe': [ColorEnum.WHITE, ColorEnum.YELLOW, ColorEnum.STRIPED],
  'light sepia brown': [ColorEnum.BROWN],
  'copenhagen blue/optic white': [ColorEnum.BLUE, ColorEnum.WHITE],
  'oat heather': [ColorEnum.BEIGE],
  'נוד': [ColorEnum.NUDE],
  'ירקרק': [ColorEnum.GREEN],
  'navy/blue stripe': [ColorEnum.NAVY, ColorEnum.BLUE, ColorEnum.STRIPED],
  '04 - cherry baze': [ColorEnum.RED],
  'lime green pattern': [ColorEnum.GREEN],
  'aloe': [ColorEnum.GREEN],
  'pollen yellow': [ColorEnum.YELLOW],
  'pearl blue': [ColorEnum.BLUE],
  'שחור/לבן': [ColorEnum.BLACK, ColorEnum.WHITE],
  'cobalt stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'בזיליקום': [ColorEnum.GREEN],
  'cream / red check': [ColorEnum.CREAM, ColorEnum.RED, ColorEnum.CHECKED],
  'rubber brown / gradient smoke to blue to orange': [ColorEnum.BROWN, ColorEnum.BLUE, ColorEnum.ORANGE],
  'dark trans champagne': [ColorEnum.BRONZE],
  'brilliant orange': [ColorEnum.ORANGE],
  '5.1 cool almond': [ColorEnum.BEIGE],
  'flag critter ivory silk': [ColorEnum.WHITE],
  'medium': [ColorEnum.GREY],
  'turquoise print': [ColorEnum.TURQUOISE],
  '3.5 ivory rose': [ColorEnum.WHITE, ColorEnum.PINK],
  'נפט': [ColorEnum.BLACK],
  'intensity 0.5': [ColorEnum.GREY],
  'cashmere creme': [ColorEnum.CREAM],
  'יין אדום': [ColorEnum.BORDEAUX],
  'icy pink / black stripe': [ColorEnum.PINK, ColorEnum.BLACK, ColorEnum.STRIPED],
  'אוקינוס': [ColorEnum.BLUE],
  'true pink': [ColorEnum.PINK],
  'יין עמוק': [ColorEnum.BORDEAUX],
  'wine': [ColorEnum.BORDEAUX],
  'classic khaki': [ColorEnum.KHAKI],
  'sky captain': [ColorEnum.BLUE],
  'olive_green': [ColorEnum.GREEN],
  'Washed Denim': [ColorEnum.WASHED_DENIM],
  'mahogany': [ColorEnum.BROWN],
  'collegiate green': [ColorEnum.GREEN],
  'transparent dark brown/gradient brown': [ColorEnum.BROWN],
  'sweet blue/white stripe': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.STRIPED],
  'matt transparent olive / g15n - g15': [ColorEnum.GREEN],
  'light blue plaid': [ColorEnum.BLUE, ColorEnum.PLAID],
  'פסים.': [ColorEnum.STRIPED],
  'trans light grey / gradient blue to transparent': [ColorEnum.GREY, ColorEnum.BLUE],
  'transparent taupe': [ColorEnum.TAUPE],
  'faded medium wash': [ColorEnum.DENIM],
  'shocking blue': [ColorEnum.BLUE],
  'rubber black/gradient smoke': [ColorEnum.BLACK],
  'אבן בהיר': [ColorEnum.STONE],
  'fort green': [ColorEnum.GREEN],
  'apple red': [ColorEnum.RED],
  'yellow print': [ColorEnum.YELLOW],
  'washed navy': [ColorEnum.NAVY],
  'calico multi stripe': [ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  '03': [ColorEnum.BLACK],
  'powder coral': [ColorEnum.CORAL],
  'navy and light heather gray': [ColorEnum.NAVY, ColorEnum.GREY],
  '69 night mauve': [ColorEnum.PURPLE],
  'semi cobalt blue': [ColorEnum.BLUE],
  'ענתיק': [ColorEnum.BEIGE],
  'team colleg gold 2': [ColorEnum.GOLD],
  'Teal': [ColorEnum.TURQUOISE],
  'light grey': [ColorEnum.GREY],
  'mushroom heather': [ColorEnum.BEIGE],
  'dessert dune': [ColorEnum.BEIGE],
  'cloud white / core black / lucid lemon': [ColorEnum.WHITE, ColorEnum.BLACK, ColorEnum.YELLOW],
  'charmed (fn)': [ColorEnum.PINK],
  'navy blue and heather gray stripe': [ColorEnum.NAVY, ColorEnum.GREY, ColorEnum.STRIPED],
  'crystal la': [ColorEnum.WHITE],
  'red ribbon': [ColorEnum.RED],
  'spring mint floral': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'foggy pink': [ColorEnum.PINK],
  'Salmon': [ColorEnum.SALMON],
  'relic tan': [ColorEnum.TAN],
  'שטיפה שחורה': [ColorEnum.BLACK],
  'navy pattern': [ColorEnum.NAVY],
  'palm court/light sage/white': [ColorEnum.GREEN, ColorEnum.WHITE],
  'classic pink check': [ColorEnum.PINK, ColorEnum.CHECKED],
  'זהב לורקס': [ColorEnum.GOLD],
  'בליצ׳': [ColorEnum.WHITE],
  
  // Additional color mappings
  'navy multi stripe': [ColorEnum.NAVY, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'audacious blue stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  '5.7 dune': [ColorEnum.BEIGE],
  'butter yellow check': [ColorEnum.YELLOW, ColorEnum.CHECKED],
  'navy blue print': [ColorEnum.NAVY],
  'driftwood brown': [ColorEnum.BROWN],
  'animal print': [ColorEnum.LEOPARD],
  'ancient white/rouge': [ColorEnum.WHITE, ColorEnum.RED],
  'light chambray': [ColorEnum.BLUE],
  'leopard print': [ColorEnum.LEOPARD],
  'medium wash denim': [ColorEnum.DENIM],
  'spark': [ColorEnum.GOLD],
  'מולטי 6': [ColorEnum.MULTICOLOR],
  'light brown': [ColorEnum.BROWN],
  'white-brown-purple': [ColorEnum.WHITE, ColorEnum.BROWN, ColorEnum.PURPLE],
  'fudge brown': [ColorEnum.BROWN],
  'jade grey/natural ivory/palm court': [ColorEnum.GREEN, ColorEnum.GREY, ColorEnum.WHITE],
  'שחור מכובס': [ColorEnum.BLACK],
  'pink organza': [ColorEnum.PINK],
  'mid grey heather': [ColorEnum.GREY],
  'washed navy with splatter': [ColorEnum.NAVY],
  'beam pink': [ColorEnum.PINK],
  'juniper green': [ColorEnum.GREEN],
  'shady stone': [ColorEnum.STONE],
  'light heather grey stripe': [ColorEnum.GREY, ColorEnum.STRIPED],
  'powder blue stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'vivacious pink': [ColorEnum.PINK],
  'black / brown': [ColorEnum.BLACK, ColorEnum.BROWN],
  '06 on repeat': [ColorEnum.BLACK],
  'washed carnival pink': [ColorEnum.PINK],
  'blue white': [ColorEnum.BLUE, ColorEnum.WHITE],
  'cream camo': [ColorEnum.CREAM, ColorEnum.CAMOUFLAGE],
  'ג\'ינס בהיר': [ColorEnum.DENIM],
  'cloudy blue': [ColorEnum.BLUE],
  'calico / harvest wheat': [ColorEnum.BEIGE],
  'beechwood / optic white stripe': [ColorEnum.BROWN, ColorEnum.WHITE, ColorEnum.STRIPED],
  '8.0 fl oz so cal': [ColorEnum.BLUE],
  'desert sand dune / dark navy stripe': [ColorEnum.BEIGE, ColorEnum.NAVY, ColorEnum.STRIPED],
  'carbon navy stripe': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'purple tint': [ColorEnum.PURPLE],
  'heathered oat': [ColorEnum.BEIGE],
  'grey heather / multi': [ColorEnum.GREY, ColorEnum.MULTICOLOR],
  'blue heather': [ColorEnum.BLUE],
  'vntg vanil': [ColorEnum.WHITE],
  'black / gradient dark orange to orange to light orange': [ColorEnum.BLACK, ColorEnum.ORANGE],
  'floral tropic pink': [ColorEnum.PINK, ColorEnum.FLORAL],
  'ecru / black stripe': [ColorEnum.BEIGE, ColorEnum.BLACK, ColorEnum.STRIPED],
  'matte shine black': [ColorEnum.BLACK],
  'dark olive plaid': [ColorEnum.GREEN, ColorEnum.PLAID],
  '17 understated': [ColorEnum.GREY],
  'בז\' מלאנז\'': [ColorEnum.BEIGE],
  'sunny orange': [ColorEnum.ORANGE],
  'snow white': [ColorEnum.WHITE],
  'rinse indg': [ColorEnum.INDIGO],
  'beige heather': [ColorEnum.BEIGE],
  'matt black/smoke': [ColorEnum.BLACK],
  'sage green camo': [ColorEnum.GREEN, ColorEnum.CAMOUFLAGE],
  'lt char': [ColorEnum.GREY],
  'lavender lux': [ColorEnum.LAVENDER],
  'silver gray': [ColorEnum.GREY],
  '102 re-see': [ColorEnum.BLUE],
  'shiny light gold/shiny black/gradient smoke': [ColorEnum.GOLD, ColorEnum.BLACK],
  'ורד אנגלי': [ColorEnum.PINK],
  'dark beige stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'כחול ולבן': [ColorEnum.BLUE, ColorEnum.WHITE],
  'trans trans light champagne / gradient smoke -silver revo': [ColorEnum.BRONZE],
  'supplier colour': [ColorEnum.MULTICOLOR],
  'ג׳ינס בהיר': [ColorEnum.DENIM],
  'paris blue': [ColorEnum.BLUE],
  'blue spell': [ColorEnum.BLUE],
  'warm butter/white': [ColorEnum.YELLOW, ColorEnum.WHITE],
  'dark mint green': [ColorEnum.GREEN],
  'נייבי פסים מלאנז\'': [ColorEnum.NAVY, ColorEnum.STRIPED],
  'navy blue and red': [ColorEnum.NAVY, ColorEnum.RED],
  'aurora ivy': [ColorEnum.GREEN],
  'חאקי בהיר': [ColorEnum.KHAKI],
  'זית בהיר': [ColorEnum.OLIVE],
  'gray blue': [ColorEnum.GREY, ColorEnum.BLUE],
  'scarlet plaid': [ColorEnum.RED, ColorEnum.PLAID],
  'navy/optic white': [ColorEnum.NAVY, ColorEnum.WHITE],
  'antracit melange': [ColorEnum.GREY],
  'white/pool party': [ColorEnum.WHITE, ColorEnum.BLUE],
  'light blue camo': [ColorEnum.BLUE, ColorEnum.CAMOUFLAGE],
  'פסים ורוד בהיר': [ColorEnum.PINK, ColorEnum.STRIPED],
  'black denim': [ColorEnum.BLACK, ColorEnum.DENIM],
  '38 nude coast': [ColorEnum.NUDE],
  'pale rose': [ColorEnum.PINK],
  'white clay': [ColorEnum.WHITE],
  'z09 soleil': [ColorEnum.YELLOW],
  'stonehedge': [ColorEnum.STONE],
  'maroon': [ColorEnum.BORDEAUX],
  'חאקי כהה': [ColorEnum.KHAKI],
  'demi': [ColorEnum.BROWN],
  '01 rendezvous': [ColorEnum.BLACK],
  'heather grey': [ColorEnum.GREY],
  'navy dot': [ColorEnum.NAVY, ColorEnum.POLKA_DOT],
  'light wash dd': [ColorEnum.DENIM],
  'shiny light gold/black beige': [ColorEnum.GOLD, ColorEnum.BLACK, ColorEnum.BEIGE],
  'לבן+פסים': [ColorEnum.WHITE, ColorEnum.STRIPED],
  'brown lines / gradient dark brown/light brown': [ColorEnum.BROWN],
  
  // Additional color mappings
  'empire blue': [ColorEnum.BLUE],
  'muslin': [ColorEnum.WHITE],
  'crepe stripe': [ColorEnum.WHITE, ColorEnum.STRIPED],
  'primary red / multi': [ColorEnum.RED, ColorEnum.MULTICOLOR],
  'dark night blue': [ColorEnum.NAVY],
  'blue rush': [ColorEnum.BLUE],
  'cardboard': [ColorEnum.BROWN],
  'blue lavender': [ColorEnum.BLUE, ColorEnum.LAVENDER],
  'dusk blue stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  '101 close up': [ColorEnum.BLACK],
  'ivory print': [ColorEnum.WHITE],
  'olive green': [ColorEnum.GREEN],
  'white/vapor': [ColorEnum.WHITE],
  'light green floral': [ColorEnum.GREEN, ColorEnum.FLORAL],
  'bright red': [ColorEnum.RED],
  'grey melange': [ColorEnum.GREY],
  'yam': [ColorEnum.ORANGE],
  'dgh solid grey': [ColorEnum.GREY],
  'light crimson': [ColorEnum.RED],
  'flora': [ColorEnum.FLORAL],
  'mustang': [ColorEnum.BROWN],
  'country brown': [ColorEnum.BROWN],
  'greystone': [ColorEnum.STONE],
  'fandango pink': [ColorEnum.PINK],
  'primary red multi stripe': [ColorEnum.RED, ColorEnum.MULTICOLOR, ColorEnum.STRIPED],
  'shiny gold /trans light champagne / gradient smoke to beige': [ColorEnum.GOLD, ColorEnum.BRONZE, ColorEnum.BEIGE],
  'vessel blue stripe': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'black light yellow demi / gradient green to yellow': [ColorEnum.BLACK, ColorEnum.YELLOW, ColorEnum.GREEN],
  'night metallic': [ColorEnum.BLACK],
  '05 medium brown ': [ColorEnum.BROWN],
  'pearly pink/mil den/bare there': [ColorEnum.PINK],
  'grey multi': [ColorEnum.GREY, ColorEnum.MULTICOLOR],
  'blush pink': [ColorEnum.PINK],
  'matt gold': [ColorEnum.GOLD],
  '5.1 bisque': [ColorEnum.BEIGE],
  'purple demi': [ColorEnum.PURPLE],
  'dusty blue': [ColorEnum.BLUE],
  '1w light': [ColorEnum.WHITE],
  'tangerine / light blue / navy': [ColorEnum.ORANGE, ColorEnum.BLUE, ColorEnum.NAVY],
  'classic beige stripe': [ColorEnum.BEIGE, ColorEnum.STRIPED],
  'shiny light gold/shiny black': [ColorEnum.GOLD, ColorEnum.BLACK],
  'navy floral': [ColorEnum.NAVY, ColorEnum.FLORAL],
  'pastel purple pattern': [ColorEnum.PURPLE],
  'light grey pattern': [ColorEnum.GREY],
  'classic beige heather': [ColorEnum.BEIGE],
  '4 fawn': [ColorEnum.BROWN],
  'pink camo': [ColorEnum.PINK, ColorEnum.CAMOUFLAGE],
  'שחור שטוף': [ColorEnum.BLACK],
  'uniform olive / multi': [ColorEnum.GREEN, ColorEnum.MULTICOLOR],
  'zero metalic': [ColorEnum.SILVER],
  'טינט': [ColorEnum.BLUE],
  'light pink pattern': [ColorEnum.PINK],
  'medium ripped destroy wash': [ColorEnum.DENIM],
  'blue coast': [ColorEnum.BLUE],
  'פסים שחור לבן': [ColorEnum.BLACK, ColorEnum.WHITE, ColorEnum.STRIPED],
  'pink multi': [ColorEnum.PINK, ColorEnum.MULTICOLOR],
  'ivory petal': [ColorEnum.WHITE],
  'night sky': [ColorEnum.BLUE],
  'espresso': [ColorEnum.BROWN],
  '1c0 silk': [ColorEnum.WHITE],
  'blue ink': [ColorEnum.BLUE],
  'dark night navy / breton dark night navy': [ColorEnum.NAVY],
  'מרווה בהיר': [ColorEnum.GREEN],
  'solid burgundy / gradient smoke': [ColorEnum.BORDEAUX],
  'white / summer plaid': [ColorEnum.WHITE, ColorEnum.PLAID],
  'fjord': [ColorEnum.BLUE],
  'dark rinse': [ColorEnum.DENIM],
  'pink print': [ColorEnum.PINK],
  'טורקיז כהה': [ColorEnum.TURQUOISE],
  'blue ink multi': [ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'dark heather grey': [ColorEnum.GREY],
  '02 jetset': [ColorEnum.BLACK],
  'utility olive': [ColorEnum.GREEN],
  'סגול לילך': [ColorEnum.PURPLE],
  'ocean trans olive to trans brown': [ColorEnum.GREEN, ColorEnum.BROWN],
  'pond': [ColorEnum.BLUE],
  'פטרול כהה': [ColorEnum.BLUE],
  'emerald pattern': [ColorEnum.GREEN],
  'black-light pink': [ColorEnum.BLACK, ColorEnum.PINK],
  'יסמין לבן': [ColorEnum.WHITE],
  'תכלת מלאנז': [ColorEnum.BLUE],
  'racer pink/white': [ColorEnum.PINK, ColorEnum.WHITE],
  'natural cognac': [ColorEnum.BROWN],
  'ivory silk / breton brilliant orange': [ColorEnum.WHITE, ColorEnum.ORANGE],
  'flax heather': [ColorEnum.BEIGE],
  'breezy blue / twill stripes': [ColorEnum.BLUE, ColorEnum.STRIPED],
  'deep navy': [ColorEnum.NAVY],
  'clear sky': [ColorEnum.BLUE],
  'rubber black': [ColorEnum.BLACK],
  'שחור נייבי': [ColorEnum.BLACK, ColorEnum.NAVY],
  'rich blue': [ColorEnum.BLUE],
  'weathered white': [ColorEnum.WHITE],
  'soft blue': [ColorEnum.BLUE],
  'butter cream': [ColorEnum.YELLOW],
  'fierce red / blue spell / pearly pink': [ColorEnum.RED, ColorEnum.BLUE, ColorEnum.PINK],
  'trans light grey / gradient smoke to dark turquoise to trans': [ColorEnum.GREY, ColorEnum.TURQUOISE],
  'light pink and oatmeal stripe': [ColorEnum.PINK, ColorEnum.BEIGE, ColorEnum.STRIPED],
  'lemonade yellow': [ColorEnum.YELLOW],
  'שחור דהוי': [ColorEnum.BLACK],
  'breezy blue/optic white stripe': [ColorEnum.BLUE, ColorEnum.WHITE, ColorEnum.STRIPED],
  
  // Additional color mappings
  'heather espresso': [ColorEnum.MOCHA],
  'sultan red': [ColorEnum.RED],
  'עוגיה': [ColorEnum.BEIGE],
  'sheer oak': [ColorEnum.BROWN],
  'light cards': [ColorEnum.WHITE],
  'trans light grey / gradient smoke to blue': [ColorEnum.GREY, ColorEnum.BLUE],
  'cloud white print': [ColorEnum.WHITE],
  'delf blue': [ColorEnum.BLUE],
  'sapphire i': [ColorEnum.BLUE],
  'horseradish': [ColorEnum.GREEN],
  'אמבר': [ColorEnum.YELLOW],
  'cherry red dot': [ColorEnum.RED, ColorEnum.POLKA_DOT],
  'tan pattern': [ColorEnum.TAN],
  'preloved ruby': [ColorEnum.RED],
  'tuscan melon multi': [ColorEnum.ORANGE, ColorEnum.MULTICOLOR],
  'faded green': [ColorEnum.GREEN],
  'tropical conversational': [ColorEnum.MULTICOLOR],
  'glory grey': [ColorEnum.GREY],
  'transparent2': [ColorEnum.TRANSPARENT],
  'navy / calico': [ColorEnum.NAVY],
  'marine': [ColorEnum.BLUE],
  'בז\' בהיר': [ColorEnum.BEIGE],
  'brown camo painter': [ColorEnum.BROWN, ColorEnum.CAMOUFLAGE],
  'dark wash': [ColorEnum.DENIM],
  'silver/gradient turquoise to transparent': [ColorEnum.SILVER, ColorEnum.TURQUOISE],
  'eqt orange': [ColorEnum.ORANGE],
  'black pocket': [ColorEnum.BLACK],
  'nantucket red': [ColorEnum.RED],
  'med grey flat': [ColorEnum.GREY],
  'שחור לבן': [ColorEnum.BLACK, ColorEnum.WHITE],
  'crystal jade': [ColorEnum.GREEN],
  'green stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  '0.1 cameo': [ColorEnum.BEIGE],
  'shiny black/smoke': [ColorEnum.BLACK],
  'cobalt blue': [ColorEnum.BLUE],
  'medium with tint': [ColorEnum.GREY],
  'demi havana': [ColorEnum.BROWN],
  'navy blue/heather gray': [ColorEnum.NAVY, ColorEnum.GREY],
  '11 stunner': [ColorEnum.PINK],
  'pulse olive': [ColorEnum.GREEN],
  'brown beige demi': [ColorEnum.BROWN, ColorEnum.BEIGE],
  'carbon navy/optic white': [ColorEnum.NAVY, ColorEnum.WHITE],
  'חציל': [ColorEnum.PURPLE],
  'פסים חאקי': [ColorEnum.KHAKI, ColorEnum.STRIPED],
  'mudstone': [ColorEnum.STONE],
  'dusty pink': [ColorEnum.PINK],
  '2 buff': [ColorEnum.BEIGE],
  'black ink': [ColorEnum.BLACK],
  'pine green': [ColorEnum.GREEN],
  'breezy blue': [ColorEnum.BLUE],
  'אנטרטיקה': [ColorEnum.WHITE],
  'core white': [ColorEnum.WHITE],
  'לבן צחור': [ColorEnum.WHITE],
  'tan camo': [ColorEnum.TAN, ColorEnum.CAMOUFLAGE],
  'faded dark wash denim': [ColorEnum.DENIM],
  'cloud heather': [ColorEnum.WHITE],
  'calico': [ColorEnum.MULTICOLOR],
  'blush yellow': [ColorEnum.YELLOW],
  'Light Denim': [ColorEnum.LIGHT_DENIM],
  'מלאנג בהיר': [ColorEnum.BEIGE],
  '5.6 ivory beige': [ColorEnum.BEIGE],
  'battle green stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'charcoal locked print': [ColorEnum.GREY],
  'ocean brown/gradient dark brown/light brown': [ColorEnum.BROWN],
  '2.5 linen': [ColorEnum.BEIGE],
  'שקד': [ColorEnum.BEIGE],
  'sandalwood check': [ColorEnum.BEIGE, ColorEnum.CHECKED],
  'מולטי 2': [ColorEnum.MULTICOLOR],
  'pink shade': [ColorEnum.PINK],
  'silver green': [ColorEnum.GREEN],
  'night flash': [ColorEnum.BLACK],
  'classic beige multi': [ColorEnum.BEIGE, ColorEnum.MULTICOLOR],
  'light grey heather stripe': [ColorEnum.GREY, ColorEnum.STRIPED],
  'vintage rose': [ColorEnum.PINK],
  'uniform olive stripe': [ColorEnum.GREEN, ColorEnum.STRIPED],
  'בלו ברי': [ColorEnum.BLUE],
  'navy blue floral': [ColorEnum.NAVY, ColorEnum.FLORAL],
  'natural': [ColorEnum.BEIGE],
  'cherry red floral': [ColorEnum.RED, ColorEnum.FLORAL],
  'פוקסיה כהה': [ColorEnum.PINK],
  '08 velvet cherry': [ColorEnum.RED],
  'global stripe': [ColorEnum.STRIPED],
  'white and green floral': [ColorEnum.WHITE, ColorEnum.GREEN, ColorEnum.FLORAL],
  'dark denim': [ColorEnum.DARK_DENIM],
  'בז\'-חום': [ColorEnum.BEIGE, ColorEnum.BROWN],
  '8.0 fl oz pure cali': [ColorEnum.BLUE],
  'faded olive': [ColorEnum.GREEN],
  'calico heather': [ColorEnum.MULTICOLOR],
  'סגול לילה': [ColorEnum.PURPLE],
  'ocean olive to peach': [ColorEnum.GREEN, ColorEnum.ORANGE],
  'optic white/blue multi': [ColorEnum.WHITE, ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'shiny black/gradient smoke': [ColorEnum.BLACK],
  'optic white / copenhagen blue stripe': [ColorEnum.WHITE, ColorEnum.BLUE, ColorEnum.STRIPED],
  'קמופלאז\'': [ColorEnum.CAMOUFLAGE],
  'raceway green': [ColorEnum.GREEN],
  'trans olive': [ColorEnum.GREEN],
  'כחול שמים': [ColorEnum.BLUE],
  'pink / red / black': [ColorEnum.PINK, ColorEnum.RED, ColorEnum.BLACK],
  'lilac sprig': [ColorEnum.LILAC],
  'קצפת': [ColorEnum.WHITE],
  
  // Additional color mappings
  'frosted evergreen multi': [ColorEnum.GREEN, ColorEnum.MULTICOLOR],
  '1.7 fl oz so cal': [],
  'power purple': [ColorEnum.PURPLE],
  'provence/optic white stripe': [ColorEnum.WHITE, ColorEnum.STRIPED],
  'palm tropic': [ColorEnum.GREEN],
  'night cargo': [ColorEnum.BLACK],
  'ocean brown': [ColorEnum.BROWN],
  'gold /trans light champagne / gradient turquoise to transparent': [ColorEnum.GOLD, ColorEnum.BRONZE, ColorEnum.TURQUOISE],
  'white grounded palm tree': [ColorEnum.WHITE, ColorEnum.GREEN],
  'הדפס חייתי': [ColorEnum.LEOPARD],
  'sandy pink': [ColorEnum.PINK],
  'athletic heather grey': [ColorEnum.GREY],
  'dark olive': [ColorEnum.GREEN],
  'deep indigo': [ColorEnum.INDIGO],
  'sail': [ColorEnum.WHITE],
  'vessel blue multi': [ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'flora medley blue multi': [ColorEnum.BLUE, ColorEnum.MULTICOLOR],
  'field green': [ColorEnum.GREEN],
  'fossil blue': [ColorEnum.BLUE],
  'wonder quartz': [ColorEnum.WHITE],
  'black-gold/gradient brown vg-31a': [ColorEnum.BLACK, ColorEnum.GOLD, ColorEnum.BROWN],
  
  // Additional Hebrew color mappings
  "אופוויט מלאנז’": [ColorEnum.OFFWHITE],
  "בז’": [ColorEnum.BEIGE],
  "תכלת מלאנז’’": [ColorEnum.BLUE],
  "נייבי מלאנז’": [ColorEnum.NAVY],
  "תכלת מלאנז’": [ColorEnum.LIGHT_BLUE],
  "בגוון ג’ינס": [ColorEnum.DENIM],
  "בז’ פסים": [ColorEnum.BEIGE, ColorEnum.STRIPED],
  "ג’ינס וינטאג’": [ColorEnum.DENIM],
  "ג’ינס כהה": [ColorEnum.DENIM],
  "בליצ’": [],
  "בז’ מלאנז’": [ColorEnum.BEIGE],
  "נייבי פסים מלאנז’": [ColorEnum.NAVY, ColorEnum.STRIPED],
}